### ISSUE TITLE
obs-webrtc-whip: Sporadic crashes on start of publication

### ISSUE THREAD

**Issue by neilyoung** [obsproject/obs-studio#10355]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/gEDnGltcYZAMlPWm

### OBS Studio Crash Log URL

crashdump.txt attached

### Expected Behavior

Shouldn't crash

### Current Behavior

If I'm not providing a "Location" header in my 201 response, an error pops up: "Connection to server failed". If I'm providing the "Location" header as shown below, OBS in 8 of 10 cases crashes badly

```
        res.contentType('application/sdp')
            .setHeader('Location', `${config.apiWHIP}/${req.params.room}/${req.params.stream}/`)
            .status(201)
            .send(answer)
```

Note: The Location header is 1:1 the resource URL. I'm having the impression, that it crashes less often, if I append some nonsense (/?4711) to the URL returned.

EDIT: These crashes might not have to do anything with Location at all, probably a premature conclusion

### Steps to Reproduce

1. Configure https://mt.votix.com/api/whip/abcde/stream as WHIP target
2. Start publishing
3.
...

**Comment by neilyoung** [comment]
Forgot crashdump

[crashdump.txt](https://github.com/obsproject/obs-studio/files/14545361/crashdump.txt)

**Comment by tt2468** [comment]
Seems to be possibly the issue fixed by <https://github.com/obsproject/obs-studio/pull/10305>

**Comment by neilyoung** [comment]
OK, I'll give 30.1 rc 1 a try

**Comment by neilyoung** [comment]
That looks pretty good. Going to close the issue for now. Thanks

**Comment by neilyoung** [comment]
But it seems, you shouldn't bother OBS with too frequent Start/Stop requests... Other issue

**Comment by neilyoung** [comment]
No, it is still crashing (or sometimes also hanging and then crashing later). Not that often, but happens.

[crashdump.txt](https://github.com/obsproject/obs-studio/files/14545713/crashdump.txt)

**Comment by RytoEX** [comment]
> No, it is still crashing (or sometimes also hanging and then crashing later). Not that often, but happens.
> 
> [crashdump.txt](https://github.com/obsproject/obs-studio/files/14545713/crashdump.txt)

#10305 landed after 30.1.0-rc1. Unless that is a recent 30.1 nightly build, you don't have that fix. Please be sure to provide a regular OBS log as well when reporting crashes.

**Comment by neilyoung** [comment]
Ah ok, sorry, I thought to have read it would already be in 30.1.0-rc1. 

> Please be sure to provide a regular OBS log as well when reporting crashes.

Certainly, but the regular log doesn't tell much in this case. It just notes the abnormal restart _after_ restart

**Comment by neilyoung** [comment]
Ok, then.

Log: https://obsproject.com/logs/Bq4TAlECRZNPi6V3

Crashdump:
[crashdump.txt](https://github.com/obsproject/obs-studio/files/14545951/crashdump.txt)

I can also provide Offer and Answer if that helps.

Crash happens immediately after "Start". I see the Offer coming and answering that.

**Comment by RytoEX** [comment]
> > Please be sure to provide a regular OBS log as well when reporting crashes.
> 
> Certainly, but the regular log doesn't tell much in this case. It just notes the abnormal restart _after_ restart

The regular log tells us the exact OBS version, which would confirm if this is RC1 or a nightly.

> Log: https://obsproject.com/logs/Bq4TAlECRZNPi6V3

As I suspected, you are testing RC1 and not a nightly. The bug you are reporting is not fixed in RC1, so it's still going to occur there. This is already fixed on master and in nightlies.
