### ISSUE TITLE
macOS Screen Capture performance degradation in macOS Sonoma

### ISSUE THREAD

**Issue by jcm93** [obsproject/obs-studio#10636]
This issue is largely additional public tracking for a known macOS-side issue, filed as FB13691162.

### Operating System Info

macOS 14

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/BaJhSqdClapbHqzK

### Expected Behavior

macOS Screen Capture performance should remain relatively consistent between macOS updates; users should not notice significant degradation in the framerate, performance, or number of simultaneous captures their system can support. macOS Screen Capture should also not significantly impact the responsiveness of macOS in general.

### Current Behavior

In macOS Sonoma, SCK (macOS Screen Capture) performance has degraded somewhat significantly. Users have noted degraded framerates, increased incidence of rendering lag for setups that used to perform acceptably, a decrease in the number of simultaneous captures their system can support, as well as degraded performance around the rest of macOS while SCK is active. The Window Capture mode is noted as being particularly unusable at present due to the amount of rendering lag it creates.

### Steps to Reproduce

1. Update to the current version of macOS Sonoma (14.4.1 as of writing).
2. Add one or multiple macOS Screen Capture sources.

### Anything else we should know?

It is apparent that these performance concerns primarily exist with the Window Capture mode.

There are also performance concerns even with the Display and Application Capture modes, though they generally seem less severe than the degradation involving Window Capture.

**Comment by Developer-Ecosystem-Engineering** [comment]
Around [here](https://github.com/obsproject/obs-studio/blob/01b61fafbf5f20e69d176e45635de3197b9e2eee/plugins/mac-capture/mac-sck-video-capture.m#L163) setting `[sc->stream_properties setCaptureResolution:SCCaptureResolutionNominal]` should workaround this issue.

**Comment by RytoEX** [comment]
cc @PatTheMav

**Comment by jcm93** [comment]
> Around [here](https://github.com/obsproject/obs-studio/blob/01b61fafbf5f20e69d176e45635de3197b9e2eee/plugins/mac-capture/mac-sck-video-capture.m#L163) setting `[sc->stream_properties setCaptureResolution:SCCaptureResolutionNominal]` should workaround this issue.

While the performance issues with Window Capture are severe, I'm not sure that implementing this would be the most ideal of workarounds, since it would reduce the resolution of the window capture by half for macOS systems using standard 2x scaling. Implementing this I think may just replace performance complaints with complaints of blurry captures.

While there are definitely people for whom this would be acceptable, i.e. those capturing a game rendering at 1080p in window with a physical pixel resolution of 2160p, I think there are just as many doing screen recordings of content that expect full display resolution from the capture.

**Comment by jcm93** [comment]
Yes, macOS 13 certainly provided retina-resolution buffers to OBS in the window capture mode. The provided resolution of captures for OBS has, to my knowledge, always been consistent (other than an issue in the Sonoma beta, since resolved). The performance while maintaining the same functionality is the sole concern here.

**Comment by dinvlad** [comment]
Any updates on this? Facing the same issue (sorry for the bump!)

**Comment by Developer-Ecosystem-Engineering** [comment]
Hi @dinvlad,

Definitive steps would be helpful. We've seen anecdotal data that capturing a Safari tab while playing a video, or doing multiple independent window captures, or capturing while editing a file in preview cause issues. When we investigate, we don't really see much difference of note between macOS 13 and macOS 14 while performing these actions within OBS. 

We remain interested in understanding the issue!

**Comment by dinvlad** [comment]
Thanks @Developer-Ecosystem-Engineering - for me it's severely lagging while doing anything at all with a single capture of the entire external display (4k@240Hz native resolution captured at 1080p@60), seemingly whether it's navigating in a browser or another app.

I don't get the same lag when I disconnect the external display and capture my Macbook M2 Max's XDR screen directly, but the GPU is still pegged at ~40% (compared to ~80% with external). Perhaps the high refresh rate on the external monitor matters?

The ~2x factor in GPU load between 4k@240Hz on the external vs ~4k@~120hz (adaptive) on internal display would seem to explain this. However, I feel like even 40% is already pretty high, for something like this (especially that it encodes only to 1080p). Or is that indeed a pretty heavy task?

**Comment by dinvlad** [comment]
I'm still experiencing this, even with just Elgato CamLink at 1080p.. It wasn't an issue in previous OBS versions, so I think there might be something more fundamental going on..

**Comment by Developer-Ecosystem-Engineering** [comment]
We remain engaged on the issue, just don't have an answer/solution quite yet. Appreciate the communities patience, we are working on it with the team.

**Comment by rafalsk** [comment]
currently the support of MacOS is utterly broken, it basically fails to capture any window each time screen goes dark or user needs to reset each view manually to recapture a particular window.
 
 How to reproduce: create a scene capturing any window. Now, each time screen goes dark, dimmed or whatever or the obs restarts one needs to choose window of same application again. By tapping the 'restart capture' button. All in all the experience and usability is way way worse than on Windows.

**Comment by dinvlad** [comment]
Is there any update on this, by any chance? Really struggling to resume my streaming, sadly because of this 🥹

**Comment by jcm93** [comment]
Via various communications with Apple, the issue of macOS Screen Capture performance specifically *regressing* between Ventura and Sonoma seems to have been addressed, to an extent, in Sonoma 14.6 and Sequoia 15.0 and onward. There are certainly changes in those versions that positively impacted performance for various capture configurations.

There are still certain capture scenarios that are particularly vexing in terms of performance. Whether these can be classified as a *regression* versus a general performance issue is relatively unclear due to the apparent difficulty of attaining a clear and unambiguous test environment by either users or Apple. It may be worth forming new issue threads to encompass specific performance concerns now, rather than using this one which dealt with the notion of a regression specifically.

Recently, performance issues with certain browser-based captures in particular were filed as FB14667613, and closed by Apple with the message that the concerns have been forwarded to the team who "will investigate performance optimization options".

@dinvlad Can you describe in more detail what precise scenario you're seeing performance issues with, with detailed steps and an OBS log capturing the issue? Having more data around specific capture scenarios that remain vexing performance-wise would be useful; and it is probably a good idea to file that directly with Apple as well.

**Comment by dinvlad** [comment]
Certainly, and thanks for responding @jcm93!

I'm on macOS Sonoma 14.6.1 (haven't tried 15.0 yet). The specific issue happens on Macbook Pro M2 Max, when using an external 4k monitor, It doesn't matter which refresh rate I set in monitor settings, even at 60 fps it's still the same issue. Any kind of "macOS Screen Capture" (Display, Window, or Application) results in a heavy whole-system lag, for all macOS UI windows (even those not captured), and accompanied by heavy CPU and GPU usage by WindowServer process in Activity Monitor (upwards of 60% utilization), and with any kind of encoding setting that I tried.

The lag disappears as soon as I _remove_ screen capture source (and not just make it invisible). It is also _not_ observed with the native ~4k display on this Macbook when the external monitor is unplugged, or the capture display is set to built-in (while keeping the external monitor plugged in). Moreover, I was able to previously (ca. Jan-Feb 2024) stream without any issues on the same Macbook, using a 4k 120 Hz OLED TV, with the same settings otherwise.

So the issue seems to nail down to capture from an external display (whether this is specific to this display model, or not - I haven't tested yet).

Please see the attached log when the external monitor is used as capture display
[2024-10-09 17-18-45.txt](https://github.com/user-attachments/files/17318973/2024-10-09.17-18-45.txt)

(If this is too much info for this thread, I'll happily create a new issue. Thanks again!)

**Comment by Developer-Ecosystem-Engineering** [comment]
> Certainly, and thanks for responding @jcm93!
> 
> I'm on macOS Sonoma 14.6.1 (haven't tried 15.0 yet). The specific issue happens on Macbook Pro M2 Max, when using an external 4k monitor, It doesn't matter which refresh rate I set in monitor settings, even at 60 fps it's still the same issue. Any kind of "macOS Screen Capture" (Display, Window, or Application) results in a heavy whole-system lag, for all macOS UI windows (even those not captured), and accompanied by heavy CPU and GPU usage by WindowServer process in Activity Monitor (upwards of 60% utilization), and with any kind of encoding setting that I tried.

> Please see the attached log when the external monitor is used as capture display [2024-10-09 17-18-45.txt](https://github.com/user-attachments/files/17318973/2024-10-09.17-18-45.txt)
> 
> (If this is too much info for this thread, I'll happily create a new issue. Thanks again!)

Hi @dinvlad,

It looks like there are four captures active in the report. 

> 17:18:47.107:     - source: 'macOS Virtual Desktop' (screen_capture)
> 17:18:47.107:     - source: 'Vivaldi Screen Cap' (sck_audio_capture)
> 17:18:47.107:     - source: 'macOS Audio Capture' (sck_audio_capture)
> 17:18:47.107:     - source: 'macOS Screen Capture' (screen_capture)

Can you confirm if you have a single scene with a single capture (of any type like you mention, Window, App, or Display) if the issue still occurs? Ideally we can add back additional captures and types to track down where the issue might be manifesting. 

The video settings used are interesting, I see 1972x1276 (3456x2234). Have you tried standard/default resolutions with the external display? Could you share the make, model and settings of that panel? This might be worth a new issue, at the moment it sounds different from what was originally reported.

**Comment by dinvlad** [comment]
Wow, thanks @Developer-Ecosystem-Engineering - while removing extra sources didn't seem to do much, changing the resolution to 4k native did! I think macOS picked the previous resolution for me because I clicked on one of the preset UI "zoom" levels that appeared comfortable enough (not too small and not too large) on this screen. However, now I'm facing the problem that at 4k the fonts etc in all apps are too small, and I'm not sure if there's a separate "scaling" macOS setting for this.

**Comment by ViRiXDreamcore** [comment]
In OBS 31.0.3 the issue persist on MacOS v14.7 

It only does this if the monitor is anything above 60 Hz. I'm using an external monitor at 2560x1440. OBS is outputting 1080p:60.

Have not tried MacOS 15.

**Comment by MisutaaAsriel** [comment]
> It looks like there are four captures active in the report.
> 
> > 17:18:47.107:     - source: 'macOS Virtual Desktop' (screen_capture)
> > 17:18:47.107:     - source: 'Vivaldi Screen Cap' (sck_audio_capture)
> > 17:18:47.107:     - source: 'macOS Audio Capture' (sck_audio_capture)
> > 17:18:47.107:     - source: 'macOS Screen Capture' (screen_capture)
> 
> Can you confirm if you have a single scene with a single capture (of any type like you mention, Window, App, or Display) if the issue still occurs? Ideally we can add back additional captures and types to track down where the issue might be manifesting.
> 
> The video settings used are interesting, I see 1972x1276 (3456x2234). Have you tried standard/default resolutions with the external display? Could you share the make, model and settings of that panel? This might be worth a new issue, at the moment it sounds different from what was originally reported.

So I'm getting lag but on the internal (MacBook) display, and using the unscaled resolution `2560 x 1664` (*set by the utility RDM.app*) results in any lag disappearing.

Currently using macOS Tahoe 26.2 on a MacBook Air M2.

This seems related to https://github.com/obsproject/obs-studio/issues/12044 which I also reported in. **Is there a problem with ScreenCaptureKit & scaled HiDPI resolutions @Developer-Ecosystem-Engineering? Checking Quartz Debugger, system performance is confirmably impacted, though this is not quite necessary to check as literally all system animations stutter or lag in these moment.**

### Addendum
1. To be clear, RDM is **Retina Display Manager** over at https://github.com/avibrazil/RDM
2. **When using "Low DPI" resolutions, issues do not occur. Using another tool, BetterDisplay, to allow setting both HiDPI & Low DPI scaled resolutions, so far, *Low DPI* scaled resolutions do not impact performance. Only HiDPI ("Retina") resolutions.**
3. This can be confirmed by setting my resolution to my preferred size of 1760x1144 **without HiDPI scaling** ("Low DPI") — Despite being the **same exact resolution as before, just without pixel doubling, performance is, in testing, no longer degraded.**

#### Issue seems to be tied to scaled HiDPI ("Pixel Doubling") modes. Using a standard variation of one's preferred resolution remedies performance issues in exchange for fuzzier text, graphics.

**Comment by Developer-Ecosystem-Engineering** [comment]
> **Is there a problem with ScreenCaptureKit & scaled HiDPI resolutions [@Developer-Ecosystem-Engineering](https://github.com/Developer-Ecosystem-Engineering)? Checking Quartz Debugger, system performance is confirmably impacted, though this is not quite necessary to check as literally all system animations stutter or lag in these moment.**

It may be more accurate to say, as the Settings | Displays panel notes when moving away from the system default resolutions,  _"Using a scaled resolution may affect performance"_. There are many reasons for this, which start much further back in the technology (and hardware) stack before we arrive at anything related to ScreenCaptureKit.

**Comment by MisutaaAsriel** [comment]
> It may be more accurate to say, as the Settings | Displays panel notes when moving away from the system default resolutions, _"Using a scaled resolution may affect performance"_. There are many reasons for this, which start much further back in the technology (and hardware) stack before we arrive at anything related to ScreenCaptureKit.

It only seems to impact HiDPI resolutions though. As mentioned, when using third party tools to set the display to a "low DPI" resolution, the issues appear to cease.

*Does in this case "scaled" mean "Retina HiDPI" scaling, rather than "a resolution which differs from native", @Developer-Ecosystem-Engineering?*

**These issues seem to primarily impact ScreenCaptureKit. Even if it's happening further back "in the stack", I've not experienced any other issues using the Apple-provided resolutions for the internal MacBook display.**

They also didn't exist at one time, with performance issues cropping up for me personally around 15.4. Whilst the nature of these issues has changed between versions, with performance issues using SCK "leveling out" with subsequent releases of macOS, degradation remains.

Whilst many of the observations [here](https://github.com/obsproject/obs-studio/issues/12044#issuecomment-2807648301) are no longer valid, and my intuition **was incorrect**, I have noticed:
- SCK sources induce extremely variable amounts of lag **if V-Sync is disabled.**
- SCK sources induce a consistent level of lag if V-Sync is enabled.
- SCK sources overall when using HiDPI resolutions **actively degrade system performance.**
- SCK sources induce no lag in early testing when display is using a "Low DPI" resolution
> [!WARNING]
> **MacBooks cannot normally access these resolutions on the internal display without third party tools.**
- These issues were not present in earlier versions of SCK with macOS.
- These issues apply to not just OBS, but are considerably relevant to its functionality.
