### ISSUE TITLE
Decklink output does not function at higher than 1080p60

### ISSUE THREAD

**Issue by chunkeyninja** [obsproject/obs-studio#11734]
### Operating System Info

Windows 11

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://obsproject.com/logs/zfDsU9rtYLAq8YPv

### Expected Behavior

When going into Tools > Decklink Output, selecting 2160p60 from the available options and pressing start, this should output a 2160p60 video over the selected SDI connection through the Decklink card.

### Current Behavior

When selecting 2160p60 (or any resolution higher than 1080p60) the output fails to start. At best currently only a 1080p60 feed can be output via the Decklink.

### Steps to Reproduce

1. Have a Blackmagic decklink card capable of 2160p60 output over SDI
2. Select output ioptions in Blackmagic Desktop Video to 2160p60
3. Attempt to output 2160p60 from Tools > Decklink Output
...

### Anything else we should know?

I have confirmed this issue is present when using the Decklink 8K pro (original and G2 variants). The problem occurs both on the current Decklink software (14.4) and when downgrading the software to the last known stable SDK that was used in the OBS decklink output function (12.0) and any version of the software inbetween. This problem appears to be consistent with all Decklinks as reported on the forum going back the last few years.

I have confirmed the 2160p output is fully functional in Wirecast as well as in Blackmagics own software so the problem is localised to OBS.

Main indication is that this feature in OBS needs to be updated to the current Decklink SDK and possibly may need some updates to work with current versions of FFmpeg which could also be the source of the problem.

**Comment by gautsch** [comment]
Can confirm - this also happens on MacOS and using Blackmagic Deign UltraStudio Mini 4K. No issues using 2160p outside of OBS, and output even shows up on the UltraStudio's screen - so it is being received; however, our switcher (M/E 4 Ultra) is unbale to process the feed.

Furthermore, as of OBS 31.1, ALL Decklink output is now broken - I've had to downgrade to 31.0.4 to get a working Decklink output again.

**Comment by RytoEX** [comment]
> Can confirm - this also happens on MacOS and using Blackmagic Deign UltraStudio Mini 4K. No issues using 2160p outside of OBS, and output even shows up on the UltraStudio's screen - so it is being received; however, our switcher (M/E 4 Ultra) is unbale to process the feed.
> 
> Furthermore, as of OBS 31.1, ALL Decklink output is now broken - I've had to downgrade to 31.0.4 to get a working Decklink output again.

While I have no insight into the first issue, the second issue has been resolved in OBS Studio 31.1.2. Let's keep this Issue scoped to the first item.

**Comment by chunkeyninja** [comment]
Bit of an interesting update, we were able to get 2160p60 to eventually output when using dual-link SDI - however it would only transmit the visual and no audio. Only by switching back to 1080p could we get audio back.

**Comment by gautsch** [comment]
> Bit of an interesting update, we were able to get 2160p60 to eventually output when using dual-link SDI - however it would only transmit the visual and no audio. Only by switching back to 1080p could we get audio back.

Ha, the opposite is the case for us - we can get audio but no video feed (our switcher is set to 2160p25). Tried both single and dual link, updated the BMD software for both the switcher and UltraStudios but no dice.

**Comment by chunkeyninja** [comment]
Bit of an update. I initially thought the issue was down to the SDK being out of date and someone in another thread recently made a patch which updated it but this didn't resolve the issue. Did some more digging and it looks like the issue is that the Decklink 8K pro only supports RGB colorspace up to 2160p30, with higher resolutions & framerates being limited to YUV colorspace. Since the Decklink output function in OBS forcibly encodes the video in BGRA, the output fails to start.

I put together a patch that switches the colorspace output to NV12 and that tested fine for me going between 2 PCs with a Decklink 8K Pro in each. Zip has the dll and the patch file with the changes. Tagging @Warchamp7 for reference.

Edit: Updated file with a fix to color conversion to use SSE2 as was experiencing some frame drops in certain circumstances. This new DLL seems to run fine even during intensive operation. Zip contains the DLL plus a diagnostic DLL (shows blank frames when missed instead of duplicates) and the patch file.

[decklink-2160p60-nv12-sse2-final.zip](https://github.com/user-attachments/files/32200345/decklink-2160p60-nv12-sse2-final.zip)
