### ISSUE TITLE
OBS Instance Crashes When Changing Size of Application Window

### ISSUE THREAD

**Issue by Type-IIx** [obsproject/obs-studio#12430]
### Operating System Info

macOS 15

### OBS Studio Version

31.1.1

### OBS Studio Log URL

https://obsproject.com/logs/1DeKalzxuZCoYwDO

### Expected Behavior

Application window dimensional change (i.e., expansion).

### Current Behavior

Crash, Sent Report to Apple

### Steps to Reproduce

1. Launch OBS Studio.app
2. Expand the Application Window

### Anything else we should know?

I provided the Discord user yamyamyamyamyamyamyamyamyamyamya (@rhenium probably – on the OBS Community Discord) with the Crash Log from Console.app dated 2025-07-24T11:23:00

Additional, macOS Screen Capture is nonfunctional, if separate issue, will provide OBS Logs on request. Export produces other captured data (i.e., audio) but .mov export is black/blank.

I could not attach the Crash Report (.ips) from Console.app since .ips file upload is not supported

![Image](https://github.com/user-attachments/assets/0631b354-3253-43dd-b250-119db4496d9c)

**Comment by PatTheMav** [comment]
You can change the crash log's file suffix to `.txt` to upload it to GitHub. Without it, we're not able to identify the precise cause of the crash.

From the provided OBS log, it seems that the renderer has produced over 60.000 error messages and there are also messages about duplicate encoder entries, which is also concerning.

I do wonder if a GPU switch takes place after OBS is launched which leads to OBS attempting to use the integrated GPU even though macOS has switched to the dedicated GPU already, but once again that's hard to say without a crash log.

**Comment by jcm93** [comment]
Possible duplicate of https://github.com/obsproject/obs-studio/issues/12413

**Comment by Type-IIx** [comment]
Since GitHub couldn't finish Uploading "OBS-2025-07-24-112325.ips.txt"...

See https://drive.proton.me/urls/0XECQ6QW9R#yP3QwrrYSpOZ

**Comment by PatTheMav** [comment]
As I have never been able to reproduce these (and similar) crashes in `gl_update`, I'd need someone who can reproduce them to go in `gl-cocoa.m` and switch out the entire function with this, in the hopes that it avoids the crash and possibly provides more detailed log output when the framebuffer object is indeed incomplete:

```C
void gl_update(gs_device_t *device)
{
    gs_swapchain_t *swap = device->cur_swap;
    NSOpenGLContext *parent = device->plat->context;
    NSOpenGLContext *context = swap->wi->context;
    struct gs_init_data info = swap->info;
    GLuint framebuffer_object = swap->wi->fbo;
    
    [parent retain];
    [context retain];

    dispatch_async(dispatch_get_main_queue(), ^() {
        if (!device || !swap || !swap->wi) {
            return;
        }

        CGLContextObj parent_obj = [parent CGLContextObj];
        CGLLockContext(parent_obj);

        CGLContextObj context_obj = [context CGLContextObj];
        CGLLockContext(context_obj);

        [context makeCurrentContext];
        [context update];
        
        gs_texture_t *texture = device_texture_create(device, info.cx, info.cy, info.format, 1, NULL, GS_RENDER_TARGET);
        
        if (!texture) {
            blog(LOG_ERROR, "gl_update (deferred): Failed to create attachment texture for framebuffer.");
            return;
        }
        
        bool success = false;

        success = gl_bind_framebuffer(GL_FRAMEBUFFER, framebuffer_object);
        
        if (!success) {
            return;
        }
        
        GLenum framebuffer_status = glCheckFramebufferStatus(GL_FRAMEBUFFER);
        
        if (framebuffer_status != GL_FRAMEBUFFER_COMPLETE) {
            switch (framebuffer_status) {
                case GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT:
                    blog(LOG_ERROR, "gl_update (deferred): Framebuffer object attachment is not complete.");
                    return;
                case GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT:
                    blog(LOG_ERROR, "gl_update (deferred): Framebuffer object is missing attachment.");
                    return;
                default:
                    blog(LOG_ERROR, "gl_update (deferred): Framebuffer object is incomplete.");
                    return;
            }
        }

        glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, texture->texture, 0);
        success = gl_success("glFrameBufferTexture2D");
        
        if (!success) {
            return;
        }
        
        glFlush();
        [NSOpenGLContext clearCurrentContext];
        
        CGLUnlockContext(context_obj);
        [context release];
        
        CGLUnlockContext(parent_obj);
        [parent release];
        
        if (swap && swap->wi && swap->wi->texture) {
            gs_texture_t *previous = swap->wi->texture;
            swap->wi->texture = texture;
            gs_texture_destroy(previous);
        }
    });
}
```

This change removes the dependency on 2 pointers within the block and instead uses copies of the same data that are retained for the block, only the update of the texture pointer remains, which is still a problem.

All operations modifying the `swap` object should probably be wrapped in a block, all dispatched to the same serial queue, to avoid race conditions between an asynchronous block on the main thread changing elements of the `swap` object while the graphics thread does the same.

**Comment by Type-IIx** [comment]
Far from Cocoa and Swift development I was reared, not to mind development. I generally only hire and (poorly) manage web devs for my site, but I can and will try my hand at compilation in the coming day(s). But I stress, not to be relied upon here!

FWIW, AWS offer [https://aws.amazon.com/ec2/instance-types/mac/](EC2 Mac Instances). 

I happen to have this info. handy in my browser history:

# See also 
- [AWS EC2 Mac – Getting Started](https://github.com/aws-samples/amazon-ec2-mac-getting-started)
- [Amazon EC2 FAQs](https://aws.amazon.com/ec2/faqs/?refid=ha_awssm-9865_ado_rank_signout#macos_workloads)

**Comment by Type-IIx** [comment]
![Image](https://github.com/user-attachments/assets/30cd064d-8a01-461d-b1b8-f4b8613302a7)

![Image](https://github.com/user-attachments/assets/10adc205-5a80-474e-9882-ae1373b551c8)

It built with your changes, but I cannot run it. _Note_ that the changes to Architectures → Architectures and Base SDK values was made after the Build Succeeded. I'm practically a layperson at this, just eager to use OBS Studio [though I have a stand-in commercial alternative].

**Comment by PatTheMav** [comment]
> It built with your changes, but I cannot run it. _Note_ that the changes to Architectures → Architectures and Base SDK values was made after the Build Succeeded. I'm practically a layperson at this, just eager to use OBS Studio [though I have a stand-in commercial alternative].

How did you configure the project? Did you follow the steps [outlined in the Wiki](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Mac#configuring-build-project)?

**Comment by Type-IIx** [comment]
I did, without specifying DCMAKE_OSX_ARCHITECTURES= for x86_64, I only gave cmake the preset flag with a macos value. 

I’ll have some time to go back later this evening, and update here.

**Comment by Type-IIx** [comment]
I intend to get to this, but at present, will be delayed.

I want to mention that AWS offer EC2 Mac Instances, including x86_64:

[Amazon EC2 Mac Instances](https://aws.amazon.com/ec2/instance-types/mac/)
[Getting Started with Amazon EC2 Mac Instances](https://github.com/aws-samples/amazon-ec2-mac-getting-started)

From [Amazon EC2 Mac Instances](https://aws.amazon.com/ec2/instance-types/mac/) : 

    # x86-based EC2 Mac instances
    x86-based EC2 Mac instances are powered by a combination of Mac mini computers, which feature
    Intel’s eighth-generation 3.2 GHz (4.6 GHz turbo) Core i7 processors, 6 physical and 12 
    logical cores, and 32 GiB of memory; and the AWS Nitro System, which provides up to 10 Gbps 
    of Amazon VPC network bandwidth and 8 Gbps of Amazon EBS storage bandwidth through high-speed 
    Thunderbolt 3 connections. x86-based EC2 Mac instances are uniquely enabled by the AWS Nitro 
    System, which makes it possible to offer Mac mini computers as fully integrated and managed 
    compute instances with Amazon VPC networking and Amazon EBS storage, just like any other 
    Amazon EC2 instance. EC2 Mac instances are available in bare-metal instance size (mac1.metal) 
    and support macOS Mojave (10.14), macOS Catalina (10.15), macOS Big Sur (11), and macOS 
    Monterey (12) as AMIs.

**Comment by Type-IIx** [comment]
This might be more useful, but I gotta move on now!

[Build obs-studio_2025-07-25T21-26-03.txt](https://github.com/user-attachments/files/21440894/Build.obs-studio_2025-07-25T21-26-03.txt)

**Comment by jcm93** [comment]
For a single arch build on Intel, you may currently have to explicitly supply the architecture. i.e:

```cmake --preset macos -DCMAKE_OSX_ARCHITECTURES=x86_64```

**Comment by Type-IIx** [comment]
I did configure cmake with `--preset macos -DCMAKE_OSX_ARCHITECTURES=x86_64`, make other configuration changes inside of XCode that seemed correct* but was unable to build due to the following errors:

![Image](https://github.com/user-attachments/assets/399ac539-ec43-4dbf-9a81-7905893e3f10)

I have attached the logs:

[Build obs-studio_2025-07-25T21-09-24.txt](https://github.com/user-attachments/files/21446066/Build.obs-studio_2025-07-25T21-09-24.txt)

*Configs:

![Image](https://github.com/user-attachments/assets/43216efb-ea2c-4947-8660-4da2d96130b3)
![Image](https://github.com/user-attachments/assets/3da8f97d-dff4-4717-94e0-693d0d584f9a)
![Image](https://github.com/user-attachments/assets/040f955e-a32a-481b-93a6-83d24159395c)
![Image](https://github.com/user-attachments/assets/2bcad71e-3580-416e-a26a-0fd0cc16096e)
![Image](https://github.com/user-attachments/assets/8ac1fba3-0710-4c93-8275-661ffeeb43a8)

- Possibly sorted in reverse order

---
_Note_: I am dealing with Proton Drive and potential data integrity problems that include _uploading_ but apparently _not_ storing this very directory! This has happened before with them, I don't believe that it's material to these issues, but FYI.

**Comment by PatTheMav** [comment]
If you're changing the build configuration, then you're also responsible for fixing any issue that arises from that. The Xcode project created by CMake will work out of the box (it is used to build the official Intel builds after all), so if it doesn't work that's due to changes you made.

In your specific case you changed the deployment target to macOS 15, which we don't support yet, because it leads specifically to the issue you experience.

---

I've implemented the suggested change and a few others in #12434 so you should be able to download the artifact for the appropriate architecture here: https://github.com/obsproject/obs-studio/actions/runs/16532598203

**Comment by Type-IIx** [comment]
> If you're changing the build configuration, then you're also responsible for fixing any issue that arises from that. The Xcode project created by CMake will work out of the box (it is used to build the official Intel builds after all), so if it doesn't work that's due to changes you made.
> 
> In your specific case you changed the deployment target to macOS 15, which we don't support yet, because it leads specifically to the issue you experience.
> 
> I've implemented the suggested change and a few others in [#12434](https://github.com/obsproject/obs-studio/pull/12434) so you should be able to download the artifact for the appropriate architecture here: https://github.com/obsproject/obs-studio/actions/runs/16532598203

You’re a weapon! I’ll check that out, thank you!

**Comment by Type-IIx** [comment]
> If you're changing the build configuration, then you're also responsible for fixing any issue that arises from that. The Xcode project created by CMake will work out of the box (it is used to build the official Intel builds after all), so if it doesn't work that's due to changes you made.
> 
> In your specific case you changed the deployment target to macOS 15, which we don't support yet, because it leads specifically to the issue you experience.
> 
> I've implemented the suggested change and a few others in [#12434](https://github.com/obsproject/obs-studio/pull/12434) so you should be able to download the artifact for the appropriate architecture here: https://github.com/obsproject/obs-studio/actions/runs/16532598203

I can no longer reproduce this issue after installing your update. Still, I can't use OBS for screen capture [never could!]

<img width="1896" height="955" alt="Image" src="https://github.com/user-attachments/assets/fa0125fd-6327-4a1e-9944-704528319d2e" />
 Unfortunately, I still can't use OBS. 

I zipped and backed-up the old OBS.app, then dragged to the Trash. Then installed the gist build.

Separate issue, anyhow. I know.

**Comment by RytoEX** [comment]
> I can no longer reproduce this issue after installing your update.

I'm going to close this as fixed then. The changes are available in the current CI/nightly builds and will be available in the upcoming release of OBS Studio.

For the other issues with screen capture, please use our support channels.
