### ISSUE TITLE
VAAPI AV1 does not send video track to WHIP output

### ISSUE THREAD

**Issue by Bleuzen** [obsproject/obs-studio#12943]
### Operating System Info

Other

### Other OS

Debian 13

### OBS Studio Version

Other

### OBS Studio Version (Other)

32.0.4

### OBS Studio Log URL

https://pastebin.com/raw/Z6FWRSka

### Expected Behavior

OBS should upload an audio and video track

### Current Behavior

OBS only uploads the audio track, video track is never sent to the streaming server

### Steps to Reproduce

1. Set video encoder to VAAPI AV1
2. Stream using WHIP

### Anything else we should know?

The streaming server logs show that it only receives the opus audio track but no video track.
I confirmed the video track is missing by looking at the network statistic of my system, it only shows a low upload rate, so the video is not sent.

It works when using H264 or HEVC. Only AV1 does not send the video track to the WHIP output.

Using AV1 CPU encoders also works, it is only broken with the VAAPI encoded AV1.

The VAAPI AV1 encoding itself works, I see the encoder usage going up when starting a stream and recording with it outputs a playable video file.

Streaming to a RTMPS output using VAAPI AV1 works.

The problem only occurs when streaming the VAAPI AV1 encoded video to a WHIP output.
Maybe the video track is not correctly packaged for WHIP?

**Comment by ghadi-rahme** [comment]
I can confirm that I have been experiencing the same issue for a while now.

I can reproduce the issue by using broadcast-box as a streaming server and OBS (obs-studio 32.0.2-2.1) running on CachyOS.

I have also noticed by looking at the wireshark data that packets are a very small when using VAAPI AV1 compared to SVT-AV1 and debugging with delve on broadcast-box also confirmed that only the audio is being received.

When debugging OBS, it seems like the video data is being sent as this code path is running and triggering breakpoints in GDB:

```
plugins/obs-webrtc/whip-output.cpp:

void WHIPOutput::Data(struct encoder_packet *packet)
{
...
...
	} else if (video_track && packet->type == OBS_ENCODER_VIDEO) {
		int64_t duration = packet->dts_usec - last_video_timestamp;
		Send(packet->data, packet->size, duration, video_track, video_sr_reporter);
		last_video_timestamp = packet->dts_usec;
	}
}
```

`packet->size` also seems to be fine and comparable to what I get when using SVT-AV1.

**Comment by ghadi-rahme** [comment]
Seems that it will be fixed in https://github.com/paullouisageneau/libdatachannel/pull/1495

**Comment by Sean-Der** [comment]
PR against obs-deps fixes this https://github.com/obsproject/obs-deps/pull/305

**Comment by kernelPanic0x** [comment]
I have a similar problem. I want to stream hardware encoded AV1 via WHIP to mediaMTX streaming server and play it via webrtc in a browser. With the SVT-AV1 software encoder it works, but with any hardware encoder (NVENC AV1 and VAAPI AV1 tested) the stream freezes after one second of video playback but the audio keeps playing. I tested this with firefox (software decoding) and brave (hardware decoding) with the same outcome.

In `brave://webrtc-internals/` i noticed that i receive frames even when the video is frozen but i get high `PLI Spam Loop (pliCount: 1085)` number and `Buffer Pileup (4,293 Unprocessed Frames)`. (https://github.com/bluenviron/mediamtx/issues/5632)

The fact that software encoded AV1 works makes me think that this is an issue with OBS (maybe libdatachannel?). I am on Arch Linux with newest libdatachannel version 0.24.3-1 and OBS version 32.1.2-3.

**Comment by Sean-Der** [comment]
This *should* be fixed by https://github.com/obsproject/obs-studio/pull/13457

@kernelPanic0x would you mind downloading a build off of that and trying? Upstream issue is https://github.com/paullouisageneau/libdatachannel/pull/1495

**Comment by kernelPanic0x** [comment]
> This _should_ be fixed by [#13457](https://github.com/obsproject/obs-studio/pull/13457)
> 
> [@kernelPanic0x](https://github.com/kernelPanic0x) would you mind downloading a build off of that and trying? Upstream issue is [paullouisageneau/libdatachannel#1495](https://github.com/paullouisageneau/libdatachannel/pull/1495)

```bash
$ ldd /usr/lib/obs-plugins/obs-webrtc.so | grep libdatachannel
	libdatachannel.so.0.24 => /usr/lib/libdatachannel.so.0.24 (0x00007f5474a00000)

$ pacman -Qi libdatachannel obs-studio
Name                     : libdatachannel
Version                  : 0.24.3-1
...
Name                     : obs-studio
Version                  : 32.1.2-3
...
```

I think my issue is a different one because I think I already have these new patches and my browser can successfully decode the first 25 frames but has a problem on the subsequent keyframes. The original issue was that there is _no_ video data available and not that it freezes after one second of playback. But I am pretty sure that the issue is in `libdatachannel` because chrome tells me that the received frames never get passed to the actual av1 decoder but only stored in jitter buffer?

**Comment by Sean-Der** [comment]
@kernelPanic0x interesting! Sorry I didn't respond sooner.

Do you see the same issue with other WHIP servers? Can you try https://github.com/glimesh/broadcast-box?

If it still happens I will add a feature to broadcast box that lets you download pcap off your session. We can use that to debug.

**Comment by kernelPanic0x** [comment]
> [@kernelPanic0x](https://github.com/kernelPanic0x) interesting! Sorry I didn't respond sooner.
> 
> Do you see the same issue with other WHIP servers? Can you try https://github.com/glimesh/broadcast-box?
> 
> If it still happens I will add a feature to broadcast box that lets you download pcap off your session. We can use that to debug.

https://github.com/glimesh/broadcast-box awesome project 👀 !

Unfortunatly, after testing it locally with broadcast-box, I have the exact same symptoms:
- NVENC h264: ✅ 
- SVT-AV1: ✅ 
- NVENC AV1: ❌ only displays first frame in browser and freezes, exactly like MediaMTX

A debugging feature for RTP with pcap would be really helpful. I did already write a little debug log in webrtc plugin from OBS to compare NVENC AV1 with SVT-AV1 OBU headers on keyframes but to my suprise NVENC seems to be in the right format (not in Annex B what i would have guessed could be the problem after some back and forth with AI). So i think I need a full RTP pcap to be able to spot the exact encoder differances to figure out what exactly is different between SVT-AV1 and NVENC AV1 🫠 .

**Comment by kernelPanic0x** [comment]
What do you mean closed? 😂 
Who can stream VAAPI AV1 or NVENC AV1 to webRTC over WHIP, because i still can't with libdatachannel 0.24.3-2 😂

**Comment by Fenrirthviti** [comment]
The deps update to fix this issue has been merged, and will be in the next release. When we merged a fix, we closed the linked issues as matter of project policy. If this is still broken after the next release, or after testing against master compiled with the latest version of our deps, then a new issue can be created or this can be reopened.

**Comment by kernelPanic0x** [comment]
Did someone test that it worked? I compiled libdatachannel myself on newset compatible branch with the new fix and it still did not work.

**Comment by kernelPanic0x** [comment]
> The deps update to fix this issue has been merged, and will be in the next release. When we merged a fix, we closed the linked issues as matter of project policy. If this is still broken after the next release, or after testing against master compiled with the latest version of our deps, then a new issue can be created or this can be reopened.

you mean a fix in obs webrtc is planned for next release?

**Comment by aMytho** [comment]
I compiled obs and the latest libdatachannel (0.24.5) from source and I was able to get it working. However, this only works in chromium. Firefox just plays the first few frames and then the video freezes.. (vaapi av1 amd rx 9060 xt linux).
