### ISSUE TITLE
Python scripting fails to load binary modules

### ISSUE THREAD

**Issue by douardda** [obsproject/obs-studio#2222]
When using a Python script in obs, loading a binary module fails due to non-exported CPython 
symbols.

I am using obs on a Linux Debian Buster.  Tested with obs compiled from current git master (ccb7d897) as well as the debian package provided in testing, aka  `obs-studio 24.0.3+dfsg1-2`.

Given the following example which tries to load the `termios` python package (a cython package):

```python
import termios
```
## Expected Behavior

I would expect this python snippet to load properly (and do nothing).

## Current Behavior

I fails with the following traceback:

```
Traceback (most recent call last):
File "/home/david/perso/elec/obs-tally/obsFirmataTally.py", line 9, in <module>
  import termios
ImportError: /usr/lib/python3.7/lib-dynload/termios.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_TypeError
```

## Steps to Reproduce
1. create a `test_import.py` script with the content being just `import termios`
2. load the script in the Tools->Scripts dialog 
3. open the Script Log dialog to see the described  traceback

## Additional information 

Using Python 3.7 from the system (3.7.3-1).

It also fails to load numpy for example.

**Comment by WizardCM** [comment]
Based on prior experience, try it with Python 3.6, and if that fails, 3.5.

**Comment by Fenrirthviti** [comment]
Ping for updates on this, as far as I am aware the scripting system prefers Python 3.6, and may not work properly with other versions. Is this issue still present with 3.6?

**Comment by douardda** [comment]
Not checked recently, I'll try ASAP (not sure exactly when I have time for this). But TBH, I'm not sure I have an easy way of testing this with other Python versions. 

The problem here is not a problem due to the version of the Python executable, it's a problem with how the embedded python interpreter is built in obs. Since I'm building these from debian's package (dget + dpkg-buildpackage), I gave a quick look at patches in the debian source package, and there are a few patches in there that could be related, (e.g. there is a potential culprit in there, 0002-Hide-internal-symbols.patch, that adds a few `visibility=hidden` flags to compile commands), but rebuilding the package without these patches did not help. 

I'll fill a bug on debian's tracker in the mean time. I'll keep you in touch here when I have feedback.

**Comment by EricWF** [comment]
I've been fighting with this bug all weekend. I can't say I've made any progress. But I would love to see it fixed.

**Comment by EricWF** [comment]
I've had cython modules fail to load with both Python 3.7 and Python 3.8.
I'm building the source at head with no additional patches.

I've found some bugs in the CMake modules that handle the SWIG bindings, Specifically that all but the last of the SWIG flags is overwritten here (https://github.com/obsproject/obs-studio/blob/master/deps/obs-scripting/obspython/CMakeLists.txt#L31-L36). But fixing that simply caused more build failures.

I'm really confused by how the python libraries are loaded on linux. They're dynamically loaded, but ,unlike Windows and Mac, on Linux we don't force load the symbols from the python library?

**Comment by EricWF** [comment]
OK. So I resolved the issue by changing `os_dlopen`

```
-       void *res = dlopen(dylib_name.array, RTLD_LAZY);
+       void *res = dlopen(dylib_name.array, RTLD_LAZY | RTLD_DEEPBIND | RTLD_GLOBAL);
``` 

Just adding RTLD_GLOBAL caused some other things to break.

**Comment by riskable** [comment]
Just curious: Would @EricWF bugfix also solve the problem where trying to do something like `import ssl` results in `ImportError: /usr/lib/python3.8/lib-dynload/_ssl.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyExc_OSError`.  They *seem* like they're the same problem but I'm not sure.

I can say for certain that the version of Python installed on my system (3.8.2) is the exact same version output when running `import platform; print(platform.python_version())` in an OBS Python script.

**Comment by douardda** [comment]
@riskable it's the same problem indeed, so if the fix provided by @EricWF works, it should also allow you to import ssl (or any other binary module).

**Comment by matteodelabre** [comment]
> OK. So I resolved the issue by changing `os_dlopen`
> 
> ```
> -       void *res = dlopen(dylib_name.array, RTLD_LAZY);
> +       void *res = dlopen(dylib_name.array, RTLD_LAZY | RTLD_DEEPBIND | RTLD_GLOBAL);
> ```
> 
> Just adding RTLD_GLOBAL caused some other things to break.

I was encountering similar errors with modules such as `math` which contain native code. I can confirm that the patch proposed by @EricWF is sufficient to fix the problem on my install as well. The line to be changed is located [here](https://github.com/obsproject/obs-studio/blob/bb890a674e8289f7be2825fbeea13c7d2f9623af/libobs/util/platform-nix.c#L74).

**Comment by WizardCM** [comment]
I appreciate the efforts of all the people here who have validated this fix. Please be sure to post in the PR that implements this change (#3335) which distro & Python version you were using when this change solved your issue.

**Comment by eli-schwartz** [comment]
> I'm really confused by how the python libraries are loaded on linux. They're dynamically loaded, but ,unlike Windows and Mac, on Linux we don't force load the symbols from the python library?

https://bugs.python.org/issue21536

Every importable module implemented in C, even the stdlib ones, no longer links to libpython but expects the interpreter to provide the needed global symbols on python >=3.8

obs-studio does not directly link to libpython, but uses dlopen, then marks it as non-global despite trying to embed a standard python interpreter. This then breaks everywhere.

**Comment by kkartaltepe** [comment]
> then marks it as non-global despite trying to embed a standard python interpreter.

To be clear obs just links it like every other system would link a normal library. It is not marked non-global, it is left unspecified.

> This then breaks everywhere.

This is better rephrased as, and then python broke linking normally for everyone.

**Comment by eli-schwartz** [comment]
> To be clear obs just links it like every other system would link a normal library. It is not marked non-global, it is left unspecified.

It doesn't *link* at all, since dlopen != link, hence the problem. :p Obeying default semantics still means the dlopen call site is saying "yes, gimme some non-global".

It's not intuitive that this should suddenly start breaking *now*, but technically it would probably feel more correct to do so either way in order to better act like a drop-in replacement for libpython, and other language interpreters sometimes behaved this way from the beginning rather than suddenly changing like python did in 3.8.

> This is better rephrased as, and then python broke linking normally for everyone.

That may be so, but my intention was to clarify that it breaks every part of the embedded interpreter e.g. wide swaths of the stdlib.

Nothing to do with which type of projects get broken or whose "fault" it is.

**Comment by kkartaltepe** [comment]
From the bug provided, the modules were compiled to support the obs use case explicitly "where the interpreter is linked with a library dlopened by an embedding application (I suppose for some kind of plugin system)". And were subsequently broken because "IHMO it's a bad usage of dlopen()". I mean its pretty clear phrasing to me.

**Comment by upgradeQ** [comment]
[`ctypes`](https://docs.python.org/3/library/ctypes.html) and [`cffi`](https://pypi.org/project/cffi/) also fail to load with `ImportError ... undefined symbol ... `. 
- python3.8 , ubuntu 20.04

**Comment by LGCW** [comment]
Ran across this thread while tracking down a funny issue with Debian Bullseye. I guess it's having trouble finding python. 

obs-scripting-python-import.h:39:10: fatal error: Python.h: No such file or directory
   39 | #include <Python.h>

**find / -iname python.h**
/usr/include/python3.9/Python.h
/usr/include/python2.7/Python.h
/usr/include/python3.8/Python.h

**Comment by guitaristtom** [comment]
Since my issue was closed and marked as duplicate, I'll do the obligatory comment on the one it's a duplicate of.

I'm still having this issue with Python 3.9.2 and OBS 27.0 RC1. I double checked the PKGBuild file and it was built against Python 3.

**Comment by volodink** [comment]
Still have this problem on OBS. Python 3.8.11, OBS fresh from repository.
Can import math, but termios or ssl - can't.
Can i switch to another python to test with?

**Comment by Fenrirthviti** [comment]
Scripting was developed and tested against Python 3.6, so using any other version is probably going to introduce a host of issues.

**Comment by volodink** [comment]
> Scripting was developed and tested against Python 3.6, so using any other version is probably going to introduce a host of issues.

How i can change interpreter in Linux?

**Comment by mlinaje** [comment]
Tested with Python 3.10 and OBS 27.1.3 clean installation and scripts do not respond. Installing Python 3.6 the problem is solved

**Comment by Chiitoo** [comment]
> Tested with Python 3.10 and OBS 27.1.3 clean installation and scripts do not respond. Installing Python 3.6 the problem is solved

I believe you'll need one of the current beta releases or 'git master' to have the fix included.

**Comment by ggregoire** [comment]
Did someone successfully run a python script on macOS?

Here are the steps I did:

```bash
brew install pyenv
pyenv install 3.6.5 # Installed Python-3.6.5 to /Users/xxxxxx/.pyenv/versions/3.6.5
```

Edited the python install path in OBS to `/Users/xxxxxx/.pyenv/versions/3.6.5`.

Reloaded the script but it still doesn't show any logs.

My script is just `print("Hello World!")`.

macOS Mojave v10.14.6
