### ISSUE TITLE
[BUG] Properties of "Window Capture (XComposite)" fills up RAM after being open for some time

### ISSUE THREAD

**Issue by bit-stone** [obsproject/obs-studio#2783]
## Platform

Operating system and version:
Ubuntu 18.04.3 (Kernel 5.6.3)

OBS Studio version:
OBS 25.0.7 (linux) from obsproject ppa
## Expected Behavior
The property window of "Window Capture (XComposite)" should not fill up RAM.

## Current Behavior
After about 30 seconds RAM usage start to go up by a rate of about 500 MB per second.
This immediately stops when the property window is closed. If it is reopened it start again right away.
I tried to capture it on video: 
https://www.youtube.com/watch?v=qh0lt3F3o9o

## Steps to Reproduce

1. Open obs-studio 
2. Add a Window Capture (XComposite)
3. Open "Properties" of the new Window Capture
4. Wait for about 30 to 60 seconds and RAM starts to fill up
5. This stops immediately once the Properties window is closed
6. On reopening the Properties window RAM immediately starts filling up again

## Additional information
This is the ouput I get from starting obs within a terminal: 

```
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: AMD Ryzen 7 1700X Eight-Core Processor
info: CPU Speed: 1768.627MHz
info: Physical Cores: 8, Logical Cores: 16
info: Physical Memory: 16005MB Total, 11078MB Free
info: Kernel Version: Linux 5.6.3-050603-generic
info: Distribution: "Ubuntu" "18.04"
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.19.6
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 25.0.7 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter X.Org AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.36.0, 5.6.3-050603-generic, LLVM 10.0.0)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 20.0.0-devel - padoka PPA, shading language 4.60
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bicubic
	fps:               60/1
	format:            NV12
	YUV mode:          601/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libDeckLinkAPI.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden

info: FFMPEG VAAPI supported
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-ouput-ui.so
info: ---------------------------------
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 11.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_0b_00.3.analog-stereo.monitor'
info: [Loaded global audio device]: 'Desktop‐Audio'
info: pulse-input: Server name: 'pulseaudio 11.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_0b_00.3.analog-stereo.monitor'
info: [Loaded global audio device]: 'Mikrofon/AUX‐Audio'
info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

info: Switched to scene 'Scene 1'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene 1':
info:     - source: 'Window Capture (Xcomposite)' (xcomposite_input)
info: ------------------------------------------------
info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /usr/share/obs/obs-studio/images/overflow.png
info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

info: xshm-input: Geometry 1920x1080 @ 0,0
info: User added source 'Screen Capture (XSHM)' (xshm_input) to scene 'Scene 1'
info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

info: xshm-input: Geometry 1920x1080 @ 1920,0
info: ---------------------------------
info: [x264 encoder: 'streaming_h264'] preset: veryfast
info: [x264 encoder: 'streaming_h264'] settings:
	rate_control: CBR
	bitrate:      6000
	buffer size:  6000
	crf:          0
	fps_num:      60
	fps_den:      1
	width:        1920
	height:       1080
	keyint:       120

info: [x264 encoder: 'streaming_h264'] custom settings: scenecut=0
info: libfdk_aac encoder created
info: libfdk_aac bitrate: 160, channels: 2
info: ==== Recording Start ===============================================
info: [ffmpeg muxer: 'adv_file_output'] Writing file '/home/bit_stone/2020-04-23 07-12-21.mkv'...
[matroska @ 0x55ee20afb400] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[matroska @ 0x55ee20afb400] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

info: [ffmpeg muxer: 'adv_file_output'] Output of file '/home/bit_stone/2020-04-23 07-12-21.mkv' stopped
info: Output 'adv_file_output': stopping
info: Output 'adv_file_output': Total frames output: 1280
info: Output 'adv_file_output': Total drawn frames: 1306 (1320 attempted)
info: Output 'adv_file_output': Number of lagged frames due to rendering lag/stalls: 14 (1,1%)
info: ==== Recording Stop ================================================
info: libfdk_aac encoder destroyed
info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

info: adding 92 milliseconds of audio buffering, total audio buffering is now 92 milliseconds (source: Desktop‐Audio)

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

info: adding 23 milliseconds of audio buffering, total audio buffering is now 116 milliseconds (source: Desktop‐Audio)

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 368): yes

```

**Comment by bit-stone** [comment]
I just noticed this on the terminal when closing obs: 
```
info: ==== Shutting down ==================================================
info: Switched to scene '(null)'
info: pulse-input: Stopped recording from 'alsa_output.pci-0000_0b_00.3.analog-stereo.monitor'
info: pulse-input: Got 151804 packets with 48090434 frames
info: pulse-input: Stopped recording from 'alsa_output.pci-0000_0b_00.3.analog-stereo.monitor'
info: pulse-input: Got 151424 packets with 48090401 frames
info: All scene data cleared
info: ------------------------------------------------
info: Freeing OBS context data
info: [Scripting] Total detached callbacks: 0
info: == Profiler Results =============================
info: run_program_init: 438,75 ms
info:  ┣OBSApp::AppInit: 2,211 ms
info:  ┃ ┗OBSApp::InitLocale: 0,978 ms
info:  ┗OBSApp::OBSInit: 362,122 ms
info:    ┣obs_startup: 21,392 ms
info:    ┗OBSBasic::OBSInit: 239,289 ms
info:      ┣OBSBasic::InitBasicConfig: 0,071 ms
info:      ┣OBSBasic::ResetAudio: 0,1 ms
info:      ┣OBSBasic::ResetVideo: 70,683 ms
info:      ┣OBSBasic::InitOBSCallbacks: 0,004 ms
info:      ┣OBSBasic::InitHotkeys: 0,037 ms
info:      ┣obs_load_all_modules: 108,95 ms
info:      ┃ ┣obs_init_module(decklink-ouput-ui.so): 0,545 ms
info:      ┃ ┣obs_init_module(frontend-tools.so): 77,426 ms
info:      ┃ ┣obs_init_module(image-source.so): 0,005 ms
info:      ┃ ┣obs_init_module(linux-alsa.so): 0,001 ms
info:      ┃ ┣obs_init_module(linux-capture.so): 0,292 ms
info:      ┃ ┣obs_init_module(linux-decklink.so): 0,13 ms
info:      ┃ ┣obs_init_module(linux-jack.so): 0,002 ms
info:      ┃ ┣obs_init_module(linux-pulseaudio.so): 0,001 ms
info:      ┃ ┣obs_init_module(linux-v4l2.so): 0,002 ms
info:      ┃ ┣obs_init_module(obs-ffmpeg.so): 0,18 ms
info:      ┃ ┃ ┗nvenc_check: 0,153 ms
info:      ┃ ┣obs_init_module(obs-filters.so): 0,016 ms
info:      ┃ ┣obs_init_module(obs-libfdk.so): 0,001 ms
info:      ┃ ┣obs_init_module(obs-outputs.so): 0,003 ms
info:      ┃ ┣obs_init_module(obs-transitions.so): 0,006 ms
info:      ┃ ┣obs_init_module(obs-x264.so): 0,001 ms
info:      ┃ ┣obs_init_module(rtmp-services.so): 0,399 ms
info:      ┃ ┣obs_init_module(text-freetype2.so): 0,007 ms
info:      ┃ ┗obs_init_module(vlc-video.so): 1,05 ms
info:      ┣OBSBasic::ResetOutputs: 0,117 ms
info:      ┣OBSBasic::CreateHotkeys: 0,025 ms
info:      ┣OBSBasic::InitService: 0,929 ms
info:      ┣OBSBasic::InitPrimitives: 0,088 ms
info:      ┗OBSBasic::Load: 30,472 ms
info: obs_hotkey_thread(25 ms): min=0,076 ms, median=0,226 ms, max=27,717 ms, 99th percentile=8,784 ms, 99,9974% below 25 ms
info: audio_thread(Audio): min=0 ms, median=0,076 ms, max=0,699 ms, 99th percentile=0,261 ms
info:  ┗receive_audio: min=0,001 ms, median=0,165 ms, max=0,489 ms, 99th percentile=0,289 ms, 0,0202678 calls per parent call
info:    ┣buffer_audio: min=0 ms, median=0,001 ms, max=0,015 ms, 99th percentile=0,003 ms
info:    ┗do_encode: min=0,082 ms, median=0,162 ms, max=0,317 ms, 99th percentile=0,281 ms
info:      ┗encode(Track1): min=0,072 ms, median=0,143 ms, max=0,285 ms, 99th percentile=0,243 ms
info: obs_graphics_thread(16,6667 ms): min=0,135 ms, median=2,688 ms, max=55,262 ms, 99th percentile=12,197 ms, 99,5363% below 16,667 ms
info:  ┣tick_sources: min=0 ms, median=2,418 ms, max=30,701 ms, 99th percentile=10,703 ms
info:  ┣output_frame: min=0,078 ms, median=0,163 ms, max=9,722 ms, 99th percentile=5,068 ms
info:  ┃ ┣gs_context(video->graphics): min=0,078 ms, median=0,163 ms, max=9,721 ms, 99th percentile=4,739 ms
info:  ┃ ┃ ┣render_video: min=0,013 ms, median=0,086 ms, max=7,474 ms, 99th percentile=4,714 ms
info:  ┃ ┃ ┃ ┣render_main_texture: min=0,011 ms, median=0,083 ms, max=0,579 ms, 99th percentile=0,119 ms
info:  ┃ ┃ ┃ ┣render_convert_texture: min=0,019 ms, median=0,029 ms, max=1,127 ms, 99th percentile=0,055 ms, 0,0200541 calls per parent call
info:  ┃ ┃ ┃ ┗stage_output_texture: min=2,938 ms, median=4,588 ms, max=6,241 ms, 99th percentile=5,038 ms, 0,0200541 calls per parent call
info:  ┃ ┃ ┣gs_flush: min=0,001 ms, median=0,065 ms, max=9,12 ms, 99th percentile=0,093 ms
info:  ┃ ┃ ┗download_frame: min=0 ms, median=0,005 ms, max=0,019 ms, 99th percentile=0,01 ms, 0,0200541 calls per parent call
info:  ┃ ┗output_video_data: min=0,274 ms, median=0,323 ms, max=1,385 ms, 99th percentile=0,643 ms, 0,0200387 calls per parent call
info:  ┗render_displays: min=0,003 ms, median=0,006 ms, max=18,67 ms, 99th percentile=3,356 ms
info: video_thread(video): min=0,001 ms, median=1,6 ms, max=8,439 ms, 99th percentile=3,297 ms
info:  ┗receive_video: min=1,012 ms, median=1,599 ms, max=8,437 ms, 99th percentile=2,917 ms
info:    ┗do_encode: min=1,011 ms, median=1,598 ms, max=8,435 ms, 99th percentile=2,916 ms
info:      ┗encode(streaming_h264): min=1,004 ms, median=1,578 ms, max=3,27 ms, 99th percentile=2,872 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: obs_hotkey_thread(25 ms): min=25,109 ms, median=25,384 ms, max=52,803 ms, 51,1879% within ±2% of 25 ms (0% lower, 48,8121% higher)
info: obs_graphics_thread(16,6667 ms): min=2,879 ms, median=16,667 ms, max=55,283 ms, 94,6455% within ±2% of 16,667 ms (2,88838% lower, 2,4661% higher)
info: =================================================
info: Number of memory leaks: 1
```

maybe this helps

**Comment by kkartaltepe** [comment]
Stop using devel drivers if you are not prepared to deal with driver bugs. Also if you intend to use devel drivers you should actually update them.

If this isnt clear you are using broken mesa drivers with a known fix committed months ago.

**Comment by bit-stone** [comment]
Thanks for your response. 
I totally forgot I had those installed. Sorry about that. 

Now I removed them using ppa-purge and rebooted several times. 
Also I removed and reinstalled obs-studio. 

But the error still exists. Does 19.2.8 also have this error? 
Or might there be still traces of the dev driver around? 
I also tried a different kernel (4.15) but the error still occurs. 

Here is the log: 
```
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: AMD Ryzen 7 1700X Eight-Core Processor
info: CPU Speed: 1881.456MHz
info: Physical Cores: 8, Logical Cores: 16
info: Physical Memory: 16005MB Total, 12909MB Free
info: Kernel Version: Linux 5.6.3-050603-generic
info: Distribution: "Ubuntu" "18.04"
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.19.6
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 25.0.7 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter X.Org AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.36.0, 5.6.3-050603-generic, LLVM 9.0.0)
info: OpenGL loaded successfully, version 4.5 (Core Profile) Mesa 19.2.8, shading language 4.50
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bicubic
	fps:               60/1
	format:            NV12
	YUV mode:          601/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libDeckLinkAPI.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden

info: FFMPEG VAAPI supported
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-ouput-ui.so
info: ---------------------------------
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 11.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_0b_00.3.analog-stereo.monitor'
info: [Loaded global audio device]: 'Desktop‐Audio'
info: pulse-input: Server name: 'pulseaudio 11.1'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_0b_00.3.analog-stereo.monitor'
info: [Loaded global audio device]: 'Mikrofon/AUX‐Audio'
info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: [BUG] Properties of "Window Capture (XComposite)" fills up RAM after being open for some time · Issue #2783 · obsproject/obs-studio - Mozilla Firefox
	class: Navigator
	Bit depth: 24
	Found proper GLXFBConfig (in 208): yes

info: Switched to scene 'Scene 1'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene 1':
info:     - source: 'Window Capture (Xcomposite)' (xcomposite_input)
info: ------------------------------------------------
Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /usr/share/obs/obs-studio/images/overflow.png
info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 208): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: conky (rapsoft-pc)
	class: conky
	Bit depth: 24
	Found proper GLXFBConfig (in 208): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: [BUG] Properties of "Window Capture (XComposite)" fills up RAM after being open for some time · Issue #2783 · obsproject/obs-studio - Mozilla Firefox
	class: Navigator
	Bit depth: 24
	Found proper GLXFBConfig (in 208): yes

info: ==== Shutting down ==================================================
info: Switched to scene '(null)'
info: pulse-input: Stopped recording from 'alsa_output.pci-0000_0b_00.3.analog-stereo.monitor'
info: pulse-input: Got 6963 packets with 2363998 frames
info: pulse-input: Stopped recording from 'alsa_output.pci-0000_0b_00.3.analog-stereo.monitor'
info: pulse-input: Got 6951 packets with 2363970 frames
info: All scene data cleared
info: ------------------------------------------------
info: Freeing OBS context data
info: [Scripting] Total detached callbacks: 0
info: == Profiler Results =============================
info: run_program_init: 633,77 ms
info:  ┣OBSApp::AppInit: 4,169 ms
info:  ┃ ┗OBSApp::InitLocale: 1,909 ms
info:  ┗OBSApp::OBSInit: 542,292 ms
info:    ┣obs_startup: 21,146 ms
info:    ┗OBSBasic::OBSInit: 399,205 ms
info:      ┣OBSBasic::InitBasicConfig: 0,077 ms
info:      ┣OBSBasic::ResetAudio: 0,115 ms
info:      ┣OBSBasic::ResetVideo: 85,627 ms
info:      ┣OBSBasic::InitOBSCallbacks: 0,004 ms
info:      ┣OBSBasic::InitHotkeys: 0,184 ms
info:      ┣obs_load_all_modules: 234,603 ms
info:      ┃ ┣obs_init_module(decklink-ouput-ui.so): 0,904 ms
info:      ┃ ┣obs_init_module(frontend-tools.so): 121,903 ms
info:      ┃ ┣obs_init_module(image-source.so): 0,006 ms
info:      ┃ ┣obs_init_module(linux-alsa.so): 0,001 ms
info:      ┃ ┣obs_init_module(linux-capture.so): 0,322 ms
info:      ┃ ┣obs_init_module(linux-decklink.so): 0,178 ms
info:      ┃ ┣obs_init_module(linux-jack.so): 0,003 ms
info:      ┃ ┣obs_init_module(linux-pulseaudio.so): 0,002 ms
info:      ┃ ┣obs_init_module(linux-v4l2.so): 0,002 ms
info:      ┃ ┣obs_init_module(obs-ffmpeg.so): 2,341 ms
info:      ┃ ┃ ┗nvenc_check: 2,308 ms
info:      ┃ ┣obs_init_module(obs-filters.so): 0,02 ms
info:      ┃ ┣obs_init_module(obs-libfdk.so): 0,002 ms
info:      ┃ ┣obs_init_module(obs-outputs.so): 0,003 ms
info:      ┃ ┣obs_init_module(obs-transitions.so): 0,008 ms
info:      ┃ ┣obs_init_module(obs-x264.so): 0,002 ms
info:      ┃ ┣obs_init_module(rtmp-services.so): 2,241 ms
info:      ┃ ┣obs_init_module(text-freetype2.so): 0,016 ms
info:      ┃ ┗obs_init_module(vlc-video.so): 2,755 ms
info:      ┣OBSBasic::ResetOutputs: 0,555 ms
info:      ┣OBSBasic::CreateHotkeys: 0,029 ms
info:      ┣OBSBasic::InitService: 2,247 ms
info:      ┣OBSBasic::InitPrimitives: 0,084 ms
info:      ┗OBSBasic::Load: 44,69 ms
info: obs_hotkey_thread(25 ms): min=0,08 ms, median=0,165 ms, max=3,791 ms, 99th percentile=0,419 ms, 100% below 25 ms
info: audio_thread(Audio): min=0 ms, median=0,075 ms, max=0,202 ms, 99th percentile=0,117 ms
info: obs_graphics_thread(16,6667 ms): min=0,136 ms, median=2,251 ms, max=37,637 ms, 99th percentile=4,93 ms, 99,9691% below 16,667 ms
info:  ┣tick_sources: min=0 ms, median=0,335 ms, max=2,973 ms, 99th percentile=0,511 ms
info:  ┣output_frame: min=0,094 ms, median=0,183 ms, max=7,785 ms, 99th percentile=0,244 ms
info:  ┃ ┗gs_context(video->graphics): min=0,094 ms, median=0,183 ms, max=7,784 ms, 99th percentile=0,244 ms
info:  ┃   ┣render_video: min=0,018 ms, median=0,079 ms, max=1,856 ms, 99th percentile=0,104 ms
info:  ┃   ┃ ┗render_main_texture: min=0,015 ms, median=0,076 ms, max=1,852 ms, 99th percentile=0,1 ms
info:  ┃   ┗gs_flush: min=0,063 ms, median=0,091 ms, max=5,909 ms, 99th percentile=0,131 ms
info:  ┗render_displays: min=0,004 ms, median=1,616 ms, max=12,968 ms, 99th percentile=4,318 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: obs_hotkey_thread(25 ms): min=25,148 ms, median=25,254 ms, max=28,856 ms, 90,2849% within ±2% of 25 ms (0% lower, 9,71509% higher)
info: obs_graphics_thread(16,6667 ms): min=12,344 ms, median=16,667 ms, max=37,642 ms, 91,1029% within ±2% of 16,667 ms (4,97374% lower, 3,92339% higher)
info: =================================================
info: Number of memory leaks: 0
```

**Comment by kkartaltepe** [comment]
https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1865536\

patch was supposedly backported to eoan and bionic.
