### ISSUE TITLE
OBS virtual camera spams log if application connects but does not actively use camera

### ISSUE THREAD

**Issue by gh-skatt** [obsproject/obs-studio#4375]
## Platform
Operating system and version: macOS 10.15.7
OBS Studio version: 26.1.2 (64 bit)
OBS Log file:

## Expected Behavior
If an application opens the virtual camera, but does not consume any frames "mac-virtualcam(DAL): Queue is full, bailing out" should be logged at reasonable intervals, not once per frame.

Opening the camera device, then not consuming frames is normal behavior for Skype for Business (and possible other video conferencing apps). In these apps it is not an error, and does not need to be logged 2.5 millon times per. day (see below).

## Current Behavior
Application opens the virtual camera, but does not consume any frames. "mac-virtualcam(DAL): Queue is full, bailing out" is logged once for every frame not consumed. So, for 30fps, this message is logged 30 times  per second, 1800 times per minute ... 2592000 times per day.

## Steps to Reproduce
1. Remove code signature on Skype for Business, "codesign --remove-signature /Applications/Skype\ for\ Business.app'. Backup the app before doing this.
2. Open 'console.app' and monitor the logs.
3. Open OBS and Start Virtual Camera. Assuming this is configured.
4. Start 'Skype for Business', go to "Audio/Video" and select OBS Virtual Camera as your camera. Close the Skype config window.
5. Excessive logging of "mac-virtualcam(DAL): Queue is full, bailing out" now starts.
6. Open the Skype for business configuration and go to "Audio/Video". Excessive logging now stops.

Whenever Skype for business actively uses the camera, either in the config window or in an active call, nothing is logged. If the app is not in any active call and not showing the camera in the settings, the error is logged once for each frame not consumed.

## Additional information
Xcode needs to be installed

**Comment by gxalpha** [comment]
Is this still the case with the current nightly? This should have been fixed in #3975

**Comment by gh-skatt** [comment]
#3975 fixes it. It explicitly removes the line responsible for this log message 👍 

It does log on every frame, see the attached log.

[mac-virtualcam.log](https://github.com/obsproject/obs-studio/files/6171359/mac-virtualcam.log)

**Comment by RytoEX** [comment]
Fixed by #3975.  I'm going to close this now.

**Comment by RytoEX** [comment]
Though admittedly, I'm confused.  That PR was merged in OBS Studio 26.1.1.  I'm not sure why you would still see this behavior in 26.1.2 you're using an older version of the plugin somehow.
