### ISSUE TITLE
Pipewire Capture image corrupt on gnome

### ISSUE THREAD

**Issue by willbernascimento** [obsproject/obs-studio#4961]
### Operating System Info

Other

### Other OS

Fedora 34

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/GqnlFazoR18EJji3

### Expected Behavior

OBS is expected to capture the selected window and likewise capture the screen correctly when launched with the dedicated graphics card using PRIME.

### Current Behavior

Currently, both windows and screenshot are broken ("blurred") using the dedicated GPU. The behavior does not occur using the integrated GPU (intel hd family)

### Steps to Reproduce

1. Open OBS using dedicated AMD GPU (AMD ATI Radeon R7 M260/M265): On Linux: `$ DRI_PRIME=1 obs`. On Fedora 34, this can be made by `right click on OBS launch icon -> `Init using dedicated GPU` 
2. Select (Source) a Window or the complete Screen for sharing
3. The Screen or Window are broken (blurred)
![dgpu-amd](https://user-images.githubusercontent.com/7853382/123890787-3a9ca700-d92e-11eb-9082-2e4ca6a1583e.png)

...

### Anything else we should know?

![igpu-intel](https://user-images.githubusercontent.com/7853382/123891037-a5e67900-d92e-11eb-975b-ae669cc62fae.png)
Using the integrated video card (Intel Family) the problem does not occur. You can access the log for intel iGPU on https://obsproject.com/logs/D2-bA72tG5uYRAmg

**Comment by angel-ayala** [comment]
Same issue here, when use the dedicated gpu with the free radeon driver present a distortionated  image.

![imagen](https://user-images.githubusercontent.com/14958503/130067783-0dbd3080-0cf5-4f7f-bbbc-27fb4a14fd87.png)

**Comment by kkartaltepe** [comment]
Does this still occur?

**Comment by willbernascimento** [comment]
Yes, the problem continues to occur oon Fedora 35. 

The log file:

14:16:18.424: Platform: Wayland
14:16:18.436: CPU Name: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
14:16:18.436: CPU Speed: 3100.000MHz
14:16:18.436: Physical Cores: 2, Logical Cores: 4
14:16:18.436: Physical Memory: 15871MB Total, 8165MB Free
14:16:18.436: Kernel Version: Linux 5.16.16-200.fc35.x86_64
14:16:18.437: Distribution: "Fedora Linux" 35
14:16:18.437: Session Type: wayland
14:16:18.440: Qt Version: 5.15.2 (runtime), 5.15.2 (compiled)
14:16:18.440: Portable mode: false
14:16:18.497: OBS 27.2.1 (linux)
14:16:18.497: ---------------------------------
14:16:19.089: ---------------------------------
14:16:19.089: audio settings reset:
14:16:19.089: 	samples per sec: 48000
14:16:19.089: 	speakers:        2
14:16:19.105: ---------------------------------
14:16:19.105: Initializing OpenGL...
14:16:19.105: Using EGL/Wayland
14:16:19.106: Initialized EGL 1.5
14:16:19.132: Loading up OpenGL on adapter AMD AMD Radeon R7 M260 (ICELAND, DRM 3.44.0, 5.16.16-200.fc35.x86_64, LLVM 13.0.0)
14:16:19.133: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 21.3.8, shading language 4.60
14:16:19.208: ---------------------------------
14:16:19.208: video settings reset:
14:16:19.208: 	base resolution:   1366x768
14:16:19.208: 	output resolution: 1092x614
14:16:19.208: 	downscale filter:  Bicubic
14:16:19.208: 	fps:               30/1
14:16:19.208: 	format:            NV12
14:16:19.208: 	YUV mode:          709/Partial
14:16:19.208: NV12 texture support not available
14:16:19.218: Audio monitoring device:
14:16:19.218: 	name: Padrão
14:16:19.218: 	id: default
14:16:19.218: ---------------------------------
14:16:19.224: Failed to load 'en-US' text for module: 'decklink-captions.so'
14:16:19.230: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
14:16:19.349: [pipewire] Available captures:
14:16:19.349: [pipewire]     - Desktop capture
14:16:19.349: [pipewire]     - Window capture
14:16:19.356: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
14:16:19.356: No blackmagic support
14:16:19.375: v4l2loopback not installed, virtual camera disabled
14:16:19.441: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente
14:16:19.441: 
14:16:19.441: FFMPEG VAAPI supported
14:16:19.491: os_dlopen(libvlc.so.5->libvlc.so.5): libvlc.so.5: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente
14:16:19.491: 
14:16:19.491: [vlc-video]: Couldn't find VLC installation, VLC video source disabled
14:16:19.491: ---------------------------------
14:16:19.491:   Loaded Modules:
14:16:19.491:     vlc-video.so
14:16:19.491:     text-freetype2.so
14:16:19.491:     rtmp-services.so
14:16:19.491:     obs-x264.so
14:16:19.491:     obs-vst.so
14:16:19.491:     obs-transitions.so
14:16:19.491:     obs-outputs.so
14:16:19.491:     obs-libfdk.so
14:16:19.491:     obs-filters.so
14:16:19.491:     obs-ffmpeg.so
14:16:19.492:     linux-v4l2.so
14:16:19.492:     linux-pulseaudio.so
14:16:19.492:     linux-jack.so
14:16:19.492:     linux-decklink.so
14:16:19.492:     linux-capture.so
14:16:19.492:     linux-alsa.so
14:16:19.492:     image-source.so
14:16:19.492:     frontend-tools.so
14:16:19.492:     decklink-ouput-ui.so
14:16:19.492:     decklink-captions.so
14:16:19.492: ---------------------------------
14:16:19.492: ==== Startup complete ===============================================
14:16:19.532: All scene data cleared
14:16:19.532: ------------------------------------------------
14:16:19.539: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.48) 15.0.0'
14:16:19.540: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
14:16:19.540: pulse-input: Started recording from 'alsa_output.pci-0000_00_1b.0.pro-output-0.monitor'
14:16:19.540: [Loaded global audio device]: 'Áudio do desktop'
14:16:19.541: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.48) 15.0.0'
14:16:19.541: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
14:16:19.541: pulse-input: Started recording from 'alsa_input.pci-0000_00_1b.0.pro-input-0'
14:16:19.541: [Loaded global audio device]: 'Mic/Aux'
14:16:19.541: Switched to scene 'Cena'
14:16:19.542: ------------------------------------------------
14:16:19.542: Loaded scenes:
14:16:19.542: - scene 'Cena':
14:16:19.542: ------------------------------------------------
14:16:20.165: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Áudio do desktop)
14:16:20.165: 
14:16:43.509: [pipewire] available cursor modes:
14:16:43.509: [pipewire]     - Metadata
14:16:43.509: [pipewire]     - Always visible
14:16:43.509: [pipewire]     - Hidden
14:16:43.509: PipeWire initialized (sender name: 1_228)
14:16:43.515: User added source 'Captura de janela (PipeWire)' (pipewire-window-capture-source) to scene 'Cena'
14:16:43.542: [pipewire] screencast session created
14:16:43.546: [pipewire] asking for window…
14:16:46.388: [pipewire] window selected, setting up screencast
14:16:46.395: [pipewire] server version: 0.3.48
14:16:46.395: [pipewire] library version: 0.3.48
14:16:46.395: [pipewire] header version: 0.3.47
14:16:46.395: [pipewire] created stream 0x5582a2298cd0
14:16:46.395: [pipewire] playing stream…
14:17:12.965: User Removed source 'Captura de janela (PipeWire)' (pipewire-window-capture-source) from scene 'Cena'
14:17:21.051: [pipewire] available cursor modes:
14:17:21.051: [pipewire]     - Metadata
14:17:21.051: [pipewire]     - Always visible
14:17:21.051: [pipewire]     - Hidden
14:17:21.051: PipeWire initialized (sender name: 1_228)
14:17:21.055: User added source 'Captura de tela (PipeWire)' (pipewire-desktop-capture-source) to scene 'Cena'
14:17:21.071: [pipewire] screencast session created
14:17:21.075: [pipewire] asking for desktop…
14:17:22.976: [pipewire] desktop selected, setting up screencast
14:17:22.982: [pipewire] server version: 0.3.48
14:17:22.982: [pipewire] library version: 0.3.48
14:17:22.982: [pipewire] header version: 0.3.47
14:17:22.982: [pipewire] created stream 0x5582a40ef2e0
14:17:22.982: [pipewire] playing stream…

**Comment by kkartaltepe** [comment]
as noted in #6609

This is a bug in gnome https://github.com/obsproject/obs-studio/issues/6609

Resolved in gnome with https://gitlab.gnome.org/GNOME/mutter/-/commit/ab3931f not available until some backporting point or gnome 43.

**Comment by JordanPlayz158** [comment]
3 days ago mutter 42.4 (https://gitlab.gnome.org/GNOME/mutter/-/tree/42.4) was released and comes with the fix and fixes the problem :partying_face:

**Comment by pgnickb** [comment]
And if I have this same issue on bare bone Sway with xdg-desktop-portal, where'd I have to look for a fix or at least further ideas on the fix.

**Comment by gegoxaren** [comment]
I have GNOME 42.4, and this still happens:
```
$ gnome-shell --version
GNOME Shell 42.4
```

![Skärmbild från 2022-10-10 16-59-43](https://user-images.githubusercontent.com/58400667/194896170-22c9f22e-37b6-4893-b6e5-e73182c2ab5e.png)

Here is the version of OBS I'm using.

```
$ flatpak run com.obsproject.Studio --version
OBS Studio - 28.0.3 (linux)
```

It seems to affect native Wayland windows, only. XWayland windows seem to not have this problem. I had the same problem with Steam streaming, but there there is a [flag you can pass](https://github.com/ValveSoftware/steam-for-linux/issues/6148#issuecomment-1176885572): `-pipewire-dmabuf` .

Is there some flag you can pass to OBS to have the same effect?

Gustav.

**Comment by kkartaltepe** [comment]
Again this isnt a bug in obs so reporting this here wont help. File bugs against gnome if you think this still hasnt been resolved in 42.4
