### ISSUE TITLE
Cannot change recording directory

### ISSUE THREAD

**Issue by The3IC** [obsproject/obs-studio#4984]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

Does not crash

### Expected Behavior

Being able to change the Output directory for recording.

### Current Behavior

Directory "Browse" button greyed out and cannot change directory

### Steps to Reproduce

1. Open OBS
2. Go to settings
3. Try to change output directory for recordings
...

### Anything else we should know?

The 27.0.1 installation overwrote the old settings.

The default video directory is a networked drive, that is mapped to Windows User directory Videos, OBS seems to expand the directory to the full network path.

![cannot change recording directory](https://user-images.githubusercontent.com/1484296/124761086-164a5700-df3a-11eb-9d9f-83adeea27fb9.JPG)

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions. In this case, you have an active output. 

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by The3IC** [comment]
> We do not use GitHub Issues for support questions. In this case, you have an active output.
> 
> Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

?? I consider this a real bug report?

**Comment by Fenrirthviti** [comment]
To clarify, the reason you can't change the path is because there is an active output (i.e. stream, recording, virtual camera, NDI, etc.) which prevents certain options from being changed. This is not a bug, this is by design. Stop all your outputs first and you can change the output path.

**Comment by The3IC** [comment]
> To clarify, the reason you can't change the path is because there is an active output (i.e. stream, recording, virtual camera, NDI, etc.) which prevents certain options from being changed. This is not a bug, this is by design. Stop all your outputs first and you can change the output path.

Sorry, but this is not the case, even immediately after OBS startup, the setting is greyed out, this has nothing to do with an active stream/recording. Nothing is going on, the problem occurs immediately after starting up 27.0.1.

**Comment by The3IC** [comment]
@WizardCM @Fenrirthviti  here is a second screenshot, as you can see, there is no recording active, and the streaming settings are enabled, just the recording settings are disabled. Screenshot taken immediately after starting OBS. 

![cannot change recording directory 2](https://user-images.githubusercontent.com/1484296/124881143-b0141180-dfd7-11eb-8d2e-3de2c0181a04.JPG)

**Comment by Fenrirthviti** [comment]
Recordings/streams are not the only outputs. Virtual Camera and several plugins, such as NDI, will count as an output being active and can be configured to autostart. Screenshots don't help. If you had stopped by the support channels for assistance as we've been telling you, we would have asked for a log file and this would have been resolved already. Everything you're showing is *exactly* what happens when there is an active output.

**Comment by The3IC** [comment]
OK, fair enough, still this looks like a change from 26, as the exactly same setup worked with no issues before upgrade to 27.

**Comment by The3IC** [comment]
Sorry to be a pain in the ass, but still would consider it a usability issue if changing the recording output directory is blocked by something else than an active recording? Over and out.

**Comment by Fenrirthviti** [comment]
It is not a change in v27. If you insist on not following proper support channels, please at least provide a log file.

**Comment by The3IC** [comment]
I was trying to get out of this discussion, thanks I have learnt my lesson, I'll stay out of this rather toxic-feeling forum. But since you asked:
- you were right, the problem was that I had forgotten the NDI on, my bad 
- I still do not see why this should prevent changing the recording directory which as no connection to the video encoding etc and only gets picked up when recording is started (if you can give a plausible *user* facing explanation, then fine, but to me this sounds like "programming by side-effect" taken to the UI)
- in some circles, bugs can also be reported against design so if "it works as designed" and the *user* experience is bad, then the design changes (seems this has been recognized at least by the person who designed/coded the Video settings page as this page clearly states there is a video stream going on which blocks changing the settings, perhaps give however did this a bit more influence?)

Out
