### ISSUE TITLE
Window decoration problems on Wayland

### ISSUE THREAD

**Issue by joshas** [obsproject/obs-studio#5843]
### Operating System Info

Other

### Other OS

Fedora 35

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/IsJ4zLmMzVcUFTv2

### Expected Behavior

OBS Studio windows on Wayland (GNOME) should be correctly decorated.

### Current Behavior

Window has no shadow.
When dragging window, titlebar changes style to "inactive".
Close button has dark hover style.

### Steps to Reproduce

1. Install OBS Studio on Fedora 35 (GNOME DE with Wayland) from rpmfusion-free-35 (RPM) repository.
2. Start OBS Studio.

### Anything else we should know?

Same issues occur on Flatpak version. Switching to Xorg fixes all mentioned issues.  

KeepassXC (which is also using QT) had similar problems in the past, but they fixed them. Might be worth looking into their source code.

**Comment by RytoEX** [comment]
This sounds like [QTBUG-74527](https://bugreports.qt.io/browse/QTBUG-74527).

cc: @GeorgesStavracas @kkartaltepe ?

**Comment by kkartaltepe** [comment]
All window decorations are handled by Qt, and I don't think we do anything to style our window in any particular way. So any mis-stylings are likely Qt bugs.

**Comment by joshas** [comment]
Not sure if useful, but starting OBS Studio with `QT_QPA_PLATFORM=xcb` environment variable set fixes window decorations issue on Wayland.

**Comment by GeorgesStavracas** [comment]
That variable doesn't "fix" window decorations; it forces OBS Studio to run as an X11 application, using the Xwayland compatibility layer. On Wayland, applications provide their own shadows, and this is usually done by the toolkit itself (Qt, GTK, etc). I think this bug is entirely on Qt side, and should be fixed there.

**Comment by GeorgesStavracas** [comment]
Thanks for the report. Let's make sure to follow up (and, potentially, fix this issue if someone is brave enough) on that [QTBUG-74527](https://bugreports.qt.io/browse/QTBUG-74527)

**Comment by joshas** [comment]
Yes, you were right; KeepassXC was not actually fixed correctly too: https://src.fedoraproject.org/rpms/keepassxc/blob/rawhide/f/xcb.patch
Will have to wait for QT to fix issue on their end.

**Comment by GeorgesStavracas** [comment]
It shouldn't be too hard (famous last words) to fix that upstream, let's see if a patch can be crafted...
