### ISSUE TITLE
(OBS 29) Upward Compressor causes bad audio distortion

### ISSUE THREAD

**Issue by loopy750** [obsproject/obs-studio#8052]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.0

### OBS Studio Log URL

-

### Expected Behavior

Audio is compressed but isn't free of distortion.

### Current Behavior

Audio distorts.

### Steps to Reproduce

1. Launch OBS (even a fresh install with no settings folder)
2. Select any type of media to record or monitor, might be easier to notice with spoken word.
3. Add and enable the Upward Compressor for that media (or Desktop Audio, whatever you're using).
4. Record and then listen back, or monitor to hear in real-time. Audio distortion should be easily noticeable, especially with the default settings. Adjusting the threshold left or right from the middle reduces the distortion.
5. Attached is a recording of a video (from YouTube) playing and adjusting the compressor settings on-the-fly.
6. Image attached is the audio visually where you can easily see most of the positive half is "clipped" off.
...

https://user-images.githubusercontent.com/35911135/212046234-6600f3ff-79a6-48e4-8db4-6ff041ff07e0.mp4

![Image1](https://user-images.githubusercontent.com/35911135/212046304-c77508ad-20e4-43a6-829f-e7c15e1680e2.jpg)

### Anything else we should know?

Anyone else able to reproduce or not reproduce? It should be easy to hear it if it's there and reproducible.

**Comment by pkviet** [comment]
check the test builds from https://github.com/obsproject/obs-studio/pull/8031
here: https://github.com/obsproject/obs-studio/pull/8031/checks
(top right: artefacts)

**Comment by loopy750** [comment]
Was it applied to that build? I'm still hearing the distortion.

**Comment by pkviet** [comment]
oops sorry, indeed i was referring to the expander.
For the upward compressor, I'm aware, there was a report but I'd argue that this means the threshold is not well positioned.

**Comment by pkviet** [comment]
Possible fix in the PR #8121 
Test builds will be available from CI. I'll post the link once building is over.

**Comment by loopy750** [comment]
I had a listen, sounds like it's a fix, nice.

**Comment by pkviet** [comment]
@loopy750 could you test the following obs-filters dll ?
[obs-filters.zip](https://github.com/obsproject/obs-studio/files/10496413/obs-filters.zip)
It has the same fix but without the knee feature. This will accelerate adoption of the fix because normally at this time we don't accept new features (like the knee).
In order to test you can either back up obs-plugins/64bit/obs-filters.dll from your Program Files/obs-studio folder or use a portable install (from https://github.com/obsproject/obs-studio/releases/download/29.0.0/OBS-Studio-29.0-Full-x64.zip ) and replace obs-filters.dll from the portable install.

**Comment by loopy750** [comment]
Ok, well, yes and no. Yes, the distortion is fixed, but there is some weird attack? issue possibly, with either of your .dll's (that I just noticed).

I'll explain the files attached:
`speech_original_#1.flac` - original file used for testing the compressor.
`speech_v29_release_#1.flac` - OBS v29 release version that distorts the audio, but doesn't have that attack issue, or whatever it is.
`speech_v29_fix_without_knee_#1.flac` - your proposed fix, that does eliminate that distortion, but does have that weird issue. You can hear in his voice after a slight pause, where he says "base unit". The best way I can describe it is, the "B" in base sounds like the Attack setting is too high, even when set to 1ms. When you listen to it, you'll understand what I mean. I'm not sure exactly what could be causing that, so I don't know what the solution could be, but it definitely wouldn't be pleasant to listen to with it occurring often.

[speech_#1.zip](https://github.com/obsproject/obs-studio/files/10496898/speech_.1.zip)

**Comment by pkviet** [comment]
@loopy750 it's because one of the commits swaps attack and release. In order to recover previous behaviour, you have to swap attack and release settings, this is because i used same attack and release for expander and upward compressor; attack is when this goes above threshold (when the fx sets out) and release is when the fx sets in (gos below threshold). The convention is that attack is when the level is increasing and release when the level is decreasing. This is not intuitive to me I must confess. We're under discussion with @norihiro who wrote the swap. In FFmpeg it seems they follow that definition of attack and release. We need to check against other upward compressors. If you have a vst for an upward compressor, you could tell us. I need to grab one first.

**Comment by loopy750** [comment]
Hmmm for this case I'm not sure if I'd be of much assistance. I can tell you if something does or doesn't sound right, but as for the solution with this current/new issue, I'm not really sure. There are guys out there who understand compressors and expanders inside out, but unfortunately I'm not one.

A slight band-aid fix I noticed is setting the Release to 1000ms. It doesn't completely eliminate the "popping", but it does reduce it a lot. But of course, not really the solution to the problem.

**Comment by pkviet** [comment]
so to be clear, currently:
- attack is applied when level increases below the threshold
- release is applied when level decreases below the threshold 
But the test dll does the reverse.
so swapping the settings (10 ms for release and 50 ms for attack) didn't fix your issue ? @loopy750 
If so it might mean we need to keep previous behaviour. Here's another dll; can you confirm it fixes all your issues including the last one ?
[obs-filters.zip](https://github.com/obsproject/obs-studio/files/10500319/obs-filters.zip)
Thanks for your help; it's really useful !

**Comment by loopy750** [comment]
> so swapping the settings (10 ms for release and 50 ms for attack) didn't fix your issue ?
Negative, I did try that, but no good, with any of the .dll's, including the one you just linked.

The "popping" effect, that follows a brief moment of silence, is still present.

**Comment by pkviet** [comment]
damnit, we're missing something then
 thx for the feedback @loopy750

**Comment by pkviet** [comment]
uh looking at the waveforms, is it really for 'base unit' an issue of too large attack ? or the reverse since the level is larger than in the original, meaning the attack_gain is itself large and the attack time is too small ?

**Comment by pkviet** [comment]
also the original level is quite high, what's your threshold ? and with the knee, there's also a popping 'Base unit' ?

**Comment by pkviet** [comment]
Here are comparison with izotope neutron 4 upward compressor with your files:
1) small attack, large release:

https://user-images.githubusercontent.com/9283407/214603447-dcd0e1b2-5741-4251-bae9-69ff220e1ae1.mp4

2) large attack, small release:

https://user-images.githubusercontent.com/9283407/214603525-92803677-f6a2-441b-99f5-0451cc834362.mp4

In the first case, it seems that the 'Base unit' is popping more. This is confirmed by inspection of the waveforms.
So it seems what you observe is in agreement with other upward compressors (or at least neutron from izotope).

Can you try with the last dll and the one just before to set a small release (5-10 ms) and large attack (100-150 ms) and see if there's any difference between the two dll ? @loopy750 
(If it's more convenient for you, we can keep the discussion in obs discord).

**Comment by loopy750** [comment]
Image:
#1 is the original, peaking at -7.7dB
#2 is OBS v29 release dll, with distortion, peaking -7.0dB
#3 is yours, around the same levels, but with that -1.7dB peak after the brief silence

I'm testing with default settings, and Knee at any setting, and the popping is still there. 

As for the question about the attack, you could be right. That was just the first explanation that came to mind, but not necessarily the correct one. It sounds like there is a "build up" during the silence, and then the attack is "too slow" to keep the audio at a sustained level. But, it could be something else instead of the attack.

![speech 1 2 3](https://user-images.githubusercontent.com/35911135/214602708-8fb792e0-cd19-4fa1-8dcd-531c5846a645.png)

**Comment by pkviet** [comment]
in dev channel, ping pkv ; we'll usher you in a private room

**Comment by pkviet** [comment]
Fixed by https://github.com/obsproject/obs-studio/pull/8121
