### ISSUE TITLE
OBS crashes when closing while streaming

### ISSUE THREAD

**Issue by Ashesh3** [obsproject/obs-studio#8300]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/fSwEikCIxcdGh2BA

### OBS Studio Crash Log URL

https://obsproject.com/logs/e5C97Y0qot3BKfh6

### Expected Behavior

When I close OBS using the cross X at the top right of the window while actively streaming, OBS should close gracefully without crashing.

### Current Behavior

When I close OBS using the cross X at the top right of the window while actively streaming, OBS crashes.

### Steps to Reproduce

1. Start OBS
2. Setup YouTube streaming using a stream key (Twitch should also work but I just use YouTube)
3. Start streaming
4. While the stream is running and active, click the X at top right of obs (or alt+f4).
5. It should exit OBS
6. A crash message box will now show up

### Anything else we should know?

This issue only occurs during streaming and not when recording or using virtual camera. If I stop the stream before closing OBS, the crash does not occur.

**Comment by RytoEX** [comment]
@Ashesh3 and @huoyan1231 

Could you please retest without the Logitech G Hub OBS plugin installed? Could you please also try retesting in OBS Studio 29.1.0 Beta 3 (or newer) and provide a new OBS crash log and new OBS log?

**Comment by huoyan1231** [comment]
> @Ashesh3 and @huoyan1231 
> 
> Could you please retest without the Logitech G Hub OBS plugin installed? Could you please also try retesting in OBS Studio 29.1.0 Beta 3 (or newer) and provide a new OBS crash log and new OBS log?

how to uninstall G hub obs plugin？

**Comment by flaeri** [comment]
@huoyan1231 Its a little bit complicated. Would you be okay joing the discord, and I can assist. Feel free to ping Flaeri (Flaeri#0001)

**Comment by Ashesh3** [comment]
![image](https://user-images.githubusercontent.com/3626859/231956079-41fc6eea-6729-4943-a99e-9d1ae94b2ee6.png)

Would deleting these 3 files be enough?

**Comment by flaeri** [comment]
@Ashesh3 You only need to remove the first one (in obs-plugins\64bit).
Make sure OBS is closed. Logitech *will* re-install this plugin automatically (on reboot perhaps), so make sure it is not present before you test. Thank you very much :)

**Comment by huoyan1231** [comment]
> @Ashesh3 You only need to remove the first one (in obs-plugins\64bit). Make sure OBS is closed. Logitech _will_ re-install this plugin automatically (on reboot perhaps), so make sure it is not present before you test. Thank you very much :)
This problem no longer seems to exist after removing the G hub plugin

**Comment by Ashesh3** [comment]
Results on `OBS 29.0.2 (64-bit, windows)`

- With `logi_obs_plugin_x64.dll` installed:
Crashed, as expected: 
[Crash 2023-04-14 11-56-08.txt](https://github.com/obsproject/obs-studio/files/11229435/Crash.2023-04-14.11-56-08.txt)

- Without `logi_obs_plugin_x64.dll`:
No crashes, a clean exit. Seems like the issue is completely resolved when removing this plugin.

**Comment by flaeri** [comment]
Oh wow, that was fast. Thank you so much.

Now as to what to do about the plugin, I am not sure. Like I said, the Logitech software (G-hub I think?) will re-install it again on reboot or re-launch of the program if memory serves. I assume uninstalling said program is not something you would want to do, as you may use it for other stuff.

**Comment by Ashesh3** [comment]
> Oh wow, that was fast. Thank you so much.
> 
> Now as to what to do about the plugin, I am not sure. Like I said, the Logitech software (G-hub I think?) will re-install it again on reboot or re-launch of the program if memory serves. I assume uninstalling said program is not something you would want to do, as you may use it for other stuff.

According to this https://obsproject.com/forum/threads/uninstall-logitech-plugin.154753/ 

It seems deleting that dll file from Logitech Ghub's folder should work, I will test it once and update this comment.

For reference, i'll be deleting these two files:
![image](https://user-images.githubusercontent.com/3626859/231962431-4414efef-ea1a-4f12-bff6-6a2820c593d0.png)

**Comment by flaeri** [comment]
Yeah, that might work temporarily, but I highly suspect that once Ghub updates, it will put those files back.

**Comment by gxalpha** [comment]
@Ashesh3 @huoyan1231 thank you for confirming that this only happens with the Logitech plugin.
As this appears to be an issue with the plugin and not with OBS itself, I will go ahead and close this. Please report it to Logitech if you can.

**Comment by Ashesh3** [comment]
For anyone else stumbling on this issue, Go to your Logitech Ghub's Profile settings (Top center) and turn off "OBS Integration". That should fix this issue.

![image](https://user-images.githubusercontent.com/3626859/233359991-1e9643ab-1b1d-434a-8c1c-939432cdda81.png)

![image](https://user-images.githubusercontent.com/3626859/233359597-0607e483-94b7-472a-9b76-c5dd60291616.png)

**Comment by CookingWithCale** [comment]
I just got over multiple months of constant crashing in OBS. Turned out to be downstream keyer, and also I'm having some issues with Max Audio Buffering. This would be solved if OBS had a built-in plugin manager, but the people who run OBS are delinquent in their duty. We still don't have any built-in shadders to replace the back stabbing from StreamFX. It's just ridiculous we don't have a plugin manager when we have companies like Logitech auto-installing plugins we manually deleted. Just because you don't have that problem because you live under a rock doesn't mean its not a problem. OBS needs new leadership.
