### ISSUE TITLE
No sound from audio monitoring

### ISSUE THREAD

**Issue by kaanelloed** [obsproject/obs-studio#8877]
### Operating System Info

Ubuntu 22.04

### Other OS

Linux Mint 21.1

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/wVZjZaNtJw0ik7Ov

### Expected Behavior

Have sound when monitoring is active

### Current Behavior

No sound when monitoring is active

### Steps to Reproduce

1. Set the Audio Monitoring of an audio source from the Audio Mixer to «Monitor Only» or «Monitor and Output»

### Anything else we should know?

Tested with the flatpak and the PPA version. Audio monitoring works in 29.0.2, but not in 29.1.0 and 29.1.1.

The audio output itself has no problem.

**Comment by Fenrirthviti** [comment]
Possibly caused by #8387, pinging @jp-bennett to take a look.

**Comment by mchilli** [comment]
can confirm this issue, i have the same behaviour.

**Comment by jp-bennett** [comment]
@mchilli and @kaanelloed can you go into settings, and audio, under advanced, and see if your Monitoring Device is set to something reasonable? It's possible that if it's still set to "Monitor of X" that value just needs refreshed to a real output device.

**Comment by tytan652** [comment]
To anyone commenting to indicate that they have this issue too, please list the distro, the type of package (PPA/Flatpak/Unofficial) that you are using.

Arch Linux, Flatpak and Unofficial, can't reproduce, monitoring works fine.

**Comment by jp-bennett** [comment]
Also curious if 29.1.0 had the same issue.

**Comment by kkartaltepe** [comment]
Not related to this issue, but related to people maybe trying to change their monitoring device. If you change your monitoring device in the settings you may need to disable and re-enable monitoring on sources afterwards as well.

**Comment by wkitty42** [comment]
i have this issue, too...
Kubuntu 20.04 with obs-studio installed from PPA:http://ppa.launchpad.net/obsproject/obs-studio/ubuntu

**Comment by kaanelloed** [comment]
> Also curious if 29.1.0 had the same issue.

Yes, 29.1.0 also has this problem.

**Comment by kaanelloed** [comment]
> Possibly caused by #8387, pinging @jp-bennett to take a look.

After installed some CI builds, it's indeed after this merge that the audio monitoring stopped working.

**Comment by kaanelloed** [comment]
I've tested the pull request and it fixes the issue on my side.

Workaround in the meanwhile: In Settings -> Audio -> Advanced, select a monitoring device other than Default. Close and reopen OBS.

**Comment by wkitty42** [comment]
On 5/10/23 9:43 PM, David wrote:
> I've tested the pull request and it fixes the issue on my side.
> 
> Workaround in the meanwhile: In Settings -> Audio -> Advanced, select a 
> monitoring device other than Default. Close and reopen OBS.


YAY! i can confirm that the workaround does enable me to hear my local Media 
Sources via my monitor(s) again... can't wait for the code fix to be released 
(via the PPA)... GG to those that found the fix(es) to the problem :)

**Comment by ponceto** [comment]
Same problem here ! The « default » monitoring source does not work. I have to choose another monitoring source and restart OBS. Damn it !

**Comment by willianholtz** [comment]
Same problem here!

Arch linux

**Comment by RytoEX** [comment]
> Same problem here!
> 
> Arch linux

Should be fixed in OBS Studio 29.1.2. Otherwise, follow the steps outlined above.

**Comment by sadranyi** [comment]
same issue changing and restarting fixed it

**Comment by WillAyd** [comment]
I am having the same issue with Ubuntu 23.04 and OBS-studio 29.1.3 installed via snap, but none of the solutions above have helped

**Comment by benjaminclay01** [comment]
Linux Mint, OBS 30.0.02, still having the same problems on the flatpak version. Changing and restarting does not fix the problem.

**Comment by kkartaltepe** [comment]
Posting "same issue" on a fixed issue is both unhelpful for us and unlikely to contribute to your problem getting resolved. Use our support channels ([Discord server](https://obsproject.com/discord)) instead where you can get help to diagnose the issue.
