### ISSUE TITLE
Target Usage settings not retained when upgrading

### ISSUE THREAD

**Issue by hoga2443** [obsproject/obs-studio#9574]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/Pbtcp0Jx0Tt4EDyn

### Expected Behavior

When upgrading from OBS 29 to OBS 30, encoder settings, such as Target Usage, should be retained.

### Current Behavior

Target Usage was reset from the assigned setting "Fast" to "TU1: Slowest (Best Quality)"

### Steps to Reproduce

1.Set an Encoder Setting Target Usage to other than Slowest (Best Quality) in OBS 29.
2.Install OBS 30

### Anything else we should know?

Other encoder settings may have failed to migrate successfully as well.  I upgraded from 29 to 30, downgraded to 29, and then upgraded to 30 again.  I can't say for certain whether the setting was changed in one of the two upgrades or in the one downgrade.

**Comment by gxalpha** [comment]
Confirmed. There are typos and missing `== 0`'s in the migration logic.

**Comment by Lain-B** [comment]
Should now be fixed

**Comment by Lain-B** [comment]
Ah okay, a misunderstanding on my part then.

**Comment by RytoEX** [comment]
This *may* be somewhat intentional. While it is not reflected in the UI, the Target Usage is silently updated in the in-memory `obs_data_t *settings` data for the QSV session and a corresponding Target Usage value based the previously selected value will be used for the encoder session. I'm not sure if it was done this way on purpose to avoid a breaking change for users who downgrade OBS for some reason, or if it was simply an oversight.

As [I commented on PR 9656](https://github.com/obsproject/obs-studio/pull/9596#issuecomment-1720270859), this could be fixed by calling `update_targetusage` from `rate_control_modified`, and it will update/overwrite the existing user settings that way (though it is invoked twice, and I didn't finish figuring that out). If I recall correctly, because the settings are updated as soon as the Settings UI is loaded, this would make downgrading no longer retain that setting, but I think that's already somewhat the case anyway for users who have saved settings with the new target usage values.

**Comment by hoga2443** [comment]
The issue appears unresolved in RC 1.  I just updated from Beta 3 to RC 1.  Target Usage was changed from TU6: Faster to TU1: Slowest (Best Quality).  If not resolved, I'm concerned a significant number of users will have recordings corrupted, as I did, if their systems cannot handle encoding at TU1.

**Comment by gxalpha** [comment]
It’s expected in this case that Beta configurations are not successfully migrated to the RC because of https://github.com/obsproject/obs-studio/pull/9647#issuecomment-1741610089.
Afaict if you’re migrated from 29.1 release to 30.0 RC1 you should now be migrated to the correct preset, *but* migration doesn’t always happen yet, which is why this issue was kept open.
