### ISSUE TITLE
OBS Studio causes the entire system to crash / reboot when clicking outside drop-down

### ISSUE THREAD

**Issue by TCROC** [obsproject/obs-studio#9612]
### Operating System Info

Other

### Other OS

Pos OS 22.04 (an Ubuntu 22.04 derivative)

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/ZYWjEhlimA4BUW7h

### OBS Studio Crash Log URL

https://obsproject.com/logs/ZYWjEhlimA4BUW7h

### Expected Behavior

I should be able to go to File -> Settings -> General -> Theme Drop-down (or any drop-down) -> then don't select any items, but just click off of the drop-down.

The drop-down should just go away.

### Current Behavior

The entire system crashes and restarts / reboots.

### Steps to Reproduce

1. File
2. Settings
3. Select Theme drop-down (or any drop-down)
4. Don't select anything else but click off of it
5. The system should crash

### Anything else we should know?

If you actually click an item from the drop-down list or press escape, it will be fine.  Here's a snip to demonstrate:

![image](https://github.com/obsproject/obs-studio/assets/24307049/9959946e-2fa3-490c-add2-a0370e0d66ae)

The red mouse with the circle around it is symbolizing an example of where to click. I would record a video but... my system crashes before I can lol.

Fortunately there are workarounds, but my goodness did it take me a minute to figure out why my system kept crashing.  Let me know if there is anything else that you need from me.  Thanks!

**Comment by TCROC** [comment]
Note: I'm using the flatpak version

**Comment by kkartaltepe** [comment]
If something more than OBS crashes, it sounds like your compositor is having a bad day and you should probably report this to them.

**Comment by TCROC** [comment]
> If something more than OBS crashes, it sounds like your compositor is having a bad day and you should probably report this to them.

I still don't think we should close this issue.  OBS Studio is the only application I've had do this.  Wouldn't this point to it being an OBS issue?

**Comment by kkartaltepe** [comment]
Poorly behaved programs must be handled correctly by your compositor, if they dont handle it correctly its their problem. And as described it likely nothing we control anyway as it would be some interaction of Qt and your compositor, neither of which we can fix here.

fwiw I cannot replicate your issue.

**Comment by tytan652** [comment]
It's a bug that was fixed in GNOME 42, it's up to Ubuntu or Pop Os to backport the fix.

**Comment by tytan652** [comment]
Duplicate of #7414

**Comment by TCROC** [comment]
@tytan652 @kkartaltepe 

So I was having several issues with my obs beyond just this crash.  I was getting bad frame stutters on Intel Quick Sync with my ARC A750.  I could not figure out how to fix those.  I also was having a hard time getting AV1 hardware encoding working.  That was when I discovered:

https://discourse.flathub.org/t/obs-studio-on-flathub-beta/690/7 

I installed obs studio 30.x with this flathub-beta:

```
 flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
 
 flatpak install --user flathub-beta com.obsproject.Studio
``` 

I then selected the beta branch.  Everything is almost working as I need it to now.  I'm still struggling to get AV1 Hardware Streaming to work (video recording seems to work) AND its not capturing my mouse cursor.

I will debug those issues further and then open a separate issue for the 30.x beta channel as it is more stable on my system so far and will be what I continue to use.

**Comment by TCROC** [comment]
Ok just found my mouse capture wasn't working because I wasn't running under wayland and I was trying to capture with pipewire.  Now mouse capture is working, but then I ran into another peculiar issue:

When initially installing under X, then swapping to Wayland, OBS would crash on open unless opened in safe mode.  I'm trying uninstalling and reinstalling under Wayland so that any cached configs get refreshed which I'm currently theorizing was the issue.

I'm just going to keep posting my findings under this thread and then organize them in a new issue since this one was already closed.

**Comment by TCROC** [comment]
Okay nevermind, it does still crash when selecting outside the dropdwon, but only on wayland
